//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "InsurancePolicyPlanController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestInsurancePolicyPlanController : TestBaseController
//Controller instance for all tests
@property InsurancePolicyPlanController* controller;
@end 


@implementation  TestInsurancePolicyPlanController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[InsurancePolicyPlanController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	




@end
