//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "OtherInsuranceTypesController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestOtherInsuranceTypesController : TestBaseController
//Controller instance for all tests
@property OtherInsuranceTypesController* controller;
@end 


@implementation  TestOtherInsuranceTypesController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[OtherInsuranceTypesController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	




@end
