//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "ElevatorInsuranceController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestElevatorInsuranceController : TestBaseController
//Controller instance for all tests
@property ElevatorInsuranceController* controller;
@end 


@implementation  TestElevatorInsuranceController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[ElevatorInsuranceController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	




@end
