//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_BASEMODELUPLOAD
#define APIMATIC_BASEMODELUPLOAD

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol BaseModelUpload
@end

@interface BaseModelUpload : JSONModel

/**
* وضعیت موفقیت درخواست
*/
@property BOOL isSuccess;

/**
* کد وضعیت درخواست
*/
@property int status;

/**
* بدنه ی اصلی درخواست که با توجه به نوع درخواست، تغییر می کند
*/
@property NSObject* message;

/**
* اطلاعات اضافه ی درخواست
*/
@property NSString* extraData;

/**
* اطلاعات خطاهای رخ داده
*/
@property NSString* exception;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif