//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "DamageType.h"

@implementation DamageType

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize title;

/**
* TODO: Write general description for this method
*/
@synthesize sortPriority;

/**
* TODO: Write general description for this method
*/
@synthesize createOn;

/**
* TODO: Write general description for this method
*/
@synthesize updateOn;

/**
* TODO: Write general description for this method
*/
@synthesize createdBy;

/**
* TODO: Write general description for this method
*/
@synthesize updatedBy;

/**
* TODO: Write general description for this method
*/
@synthesize createOnPersianDate;

/**
* TODO: Write general description for this method
*/
@synthesize updateOnPersianDate;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"title": @"title",
        @"sortPriority": @"sortPriority",
        @"createOn": @"createOn",
        @"updateOn": @"updateOn",
        @"createdBy": @"createdBy",
        @"updatedBy": @"updatedBy",
        @"createOnPersianDate": @"createOnPersianDate",
        @"updateOnPersianDate": @"updateOnPersianDate"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end