//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "DeviceBrandTypes.h"

@implementation DeviceBrandTypes

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize title;

/**
* TODO: Write general description for this method
*/
@synthesize deviceGroup;

/**
* TODO: Write general description for this method
*/
@synthesize deviceTypeId;

/**
* TODO: Write general description for this method
*/
@synthesize deviceBrandId;

/**
* TODO: Write general description for this method
*/
@synthesize createOn;

/**
* TODO: Write general description for this method
*/
@synthesize updateOn;

/**
* TODO: Write general description for this method
*/
@synthesize createdBy;

/**
* TODO: Write general description for this method
*/
@synthesize updatedBy;

/**
* TODO: Write general description for this method
*/
@synthesize createOnPersianDate;

/**
* TODO: Write general description for this method
*/
@synthesize updateOnPersianDate;

/**
* TODO: Write general description for this method
*/
@synthesize deviceTypeTitle;

/**
* TODO: Write general description for this method
*/
@synthesize deviceBrandTitle;

/**
* TODO: Write general description for this method
*/
@synthesize deviceTypeBrandModelTitle;

/**
* TODO: Write general description for this method
*/
@synthesize deviceBrandIds;

/**
* TODO: Write general description for this method
*/
@synthesize deviceBrandsTitle;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"title": @"title",
        @"deviceGroup": @"deviceGroup",
        @"deviceTypeId": @"deviceTypeId",
        @"deviceBrandId": @"deviceBrandId",
        @"createOn": @"createOn",
        @"updateOn": @"updateOn",
        @"createdBy": @"createdBy",
        @"updatedBy": @"updatedBy",
        @"createOnPersianDate": @"createOnPersianDate",
        @"updateOnPersianDate": @"updateOnPersianDate",
        @"deviceTypeTitle": @"deviceTypeTitle",
        @"deviceBrandTitle": @"deviceBrandTitle",
        @"deviceTypeBrandModelTitle": @"deviceTypeBrandModelTitle",
        @"deviceBrandIds": @"deviceBrandIds",
        @"deviceBrandsTitle": @"deviceBrandsTitle"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end