//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_DEVICEBRANDTYPES
#define APIMATIC_DEVICEBRANDTYPES

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol DeviceBrandTypes
@end

@interface DeviceBrandTypes : JSONModel

/**
* TODO: Write general description for this field
*/
@property int mid;

/**
* TODO: Write general description for this field
*/
@property NSString* title;

/**
* TODO: Write general description for this field
*/
@property int deviceGroup;

/**
* TODO: Write general description for this field
*/
@property NSNumber* deviceTypeId;

/**
* TODO: Write general description for this field
*/
@property NSString* deviceBrandId;

/**
* TODO: Write general description for this field
*/
@property NSString* createOn;

/**
* TODO: Write general description for this field
*/
@property NSString* updateOn;

/**
* TODO: Write general description for this field
*/
@property NSString* createdBy;

/**
* TODO: Write general description for this field
*/
@property NSString* updatedBy;

/**
* TODO: Write general description for this field
*/
@property NSString* createOnPersianDate;

/**
* TODO: Write general description for this field
*/
@property NSString* updateOnPersianDate;

/**
* TODO: Write general description for this field
*/
@property NSString* deviceTypeTitle;

/**
* TODO: Write general description for this field
*/
@property NSString* deviceBrandTitle;

/**
* TODO: Write general description for this field
*/
@property NSString* deviceTypeBrandModelTitle;

/**
* TODO: Write general description for this field
*/
@property NSArray* deviceBrandIds;

/**
* TODO: Write general description for this field
*/
@property NSString* deviceBrandsTitle;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif