//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_EARTHQUAKE
#define APIMATIC_EARTHQUAKE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ComboDataModel.h"
#import "InsurancePolicyTerm.h"
#import "EverySquareMeterCoverage.h"
#import "Province.h"
#import "ShippingType.h"
#import "PostType.h"
#import "InsurancePolicyCondition.h"
#import "InsuranceDataFireInsurance.h"


//protocol defined for deserialization of JSON
@protocol Earthquake
@end

@interface Earthquake : JSONModel

/**
* TODO: Write general description for this field
*/
@property BOOL hasPlan;

/**
* TODO: Write general description for this field
*/
@property int insuranceCentreProvinceId;

/**
* TODO: Write general description for this field
*/
@property int insuranceCentreCityId;

/**
* TODO: Write general description for this field
*/
@property NSArray<ComboDataModel> * insuranceCentreCities;

/**
* TODO: Write general description for this field
*/
@property NSArray<ComboDataModel> * buildingTypes;

/**
* TODO: Write general description for this field
*/
@property NSArray<ComboDataModel> * skeletonTypeBuildings;

/**
* TODO: Write general description for this field
*/
@property NSArray<ComboDataModel> * buildingUseTypes;

/**
* TODO: Write general description for this field
*/
@property NSArray<InsurancePolicyTerm> * insurancePolicyTerms;

/**
* TODO: Write general description for this field
*/
@property NSArray* insuranceExtraCoverage;

/**
* TODO: Write general description for this field
*/
@property NSArray<EverySquareMeterCoverage> * everySquareMeterCoverage;

/**
* TODO: Write general description for this field
*/
@property NSArray<Province> * provinces;

/**
* TODO: Write general description for this field
*/
@property NSArray* cities;

/**
* TODO: Write general description for this field
*/
@property NSArray* cityRegions;

/**
* TODO: Write general description for this field
*/
@property NSArray<ShippingType> * shippingTypes;

/**
* TODO: Write general description for this field
*/
@property NSArray<PostType> * postTypes;

/**
* TODO: Write general description for this field
*/
@property InsurancePolicyCondition* insurancePolicyCondition;

/**
* TODO: Write general description for this field
*/
@property InsuranceDataFireInsurance* insuranceData;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif