//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "ElectronicEquipmentInsurancePolicyExtendView.h"

@implementation ElectronicEquipmentInsurancePolicyExtendView

/**
* شناسه ی نوع دستگاه
*/
@synthesize deviceTypeId;

/**
* شناسه ی برند دستگاه
*/
@synthesize deviceBrandId;

/**
* شناسه ی مدل دستگاه
*/
@synthesize deviceModelId;

/**
* سریال دستگاه
*/
@synthesize deviceSerial;

/**
* سال ساخت دستگاه
*/
@synthesize buildYear;

/**
* TODO: Write general description for this method
*/
@synthesize deviceValue;

/**
* TODO: Write general description for this method
*/
@synthesize franchisee;

/**
* TODO: Write general description for this method
*/
@synthesize hasWarranty;

/**
* TODO: Write general description for this method
*/
@synthesize warrantyCompany;

/**
* TODO: Write general description for this method
*/
@synthesize serialInsuranceCard;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaBehindDeviceId;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaBehindDeviceUrl;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaOnDeviceId;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaOnDeviceUrl;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaDeviceBoxId;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaDeviceBoxUrl;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCoverageIds;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCoveragePrice;

/**
* TODO: Write general description for this method
*/
@synthesize basePremium;

/**
* TODO: Write general description for this method
*/
@synthesize allPremium;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyDiscountRate;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize coupenDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize allDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize exchangePremium;

/**
* TODO: Write general description for this method
*/
@synthesize deviceTypeTitle;

/**
* TODO: Write general description for this method
*/
@synthesize deviceBrandTitle;

/**
* TODO: Write general description for this method
*/
@synthesize deviceModelTitle;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"deviceTypeId": @"deviceTypeId",
        @"deviceBrandId": @"deviceBrandId",
        @"deviceModelId": @"deviceModelId",
        @"deviceSerial": @"deviceSerial",
        @"buildYear": @"buildYear",
        @"deviceValue": @"deviceValue",
        @"franchisee": @"franchisee",
        @"hasWarranty": @"hasWarranty",
        @"warrantyCompany": @"warrantyCompany",
        @"serialInsuranceCard": @"serialInsuranceCard",
        @"metaMediaBehindDeviceId": @"metaMediaBehindDeviceId",
        @"metaMediaBehindDeviceUrl": @"metaMediaBehindDeviceUrl",
        @"metaMediaOnDeviceId": @"metaMediaOnDeviceId",
        @"metaMediaOnDeviceUrl": @"metaMediaOnDeviceUrl",
        @"metaMediaDeviceBoxId": @"metaMediaDeviceBoxId",
        @"metaMediaDeviceBoxUrl": @"metaMediaDeviceBoxUrl",
        @"_InsuranceCoverageIds": @"insuranceCoverageIds",
        @"insuranceCoveragePrice": @"insuranceCoveragePrice",
        @"basePremium": @"basePremium",
        @"allPremium": @"allPremium",
        @"insuranceCompanyDiscountRate": @"insuranceCompanyDiscountRate",
        @"insuranceCompanyDiscount": @"insuranceCompanyDiscount",
        @"insuranceCentreDiscount": @"insuranceCentreDiscount",
        @"coupenDiscount": @"coupenDiscount",
        @"allDiscount": @"allDiscount",
        @"exchangePremium": @"exchangePremium",
        @"deviceTypeTitle": @"deviceTypeTitle",
        @"deviceBrandTitle": @"deviceBrandTitle",
        @"deviceModelTitle": @"deviceModelTitle"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end