//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_ELECTRONICEQUIPMENTINSURANCE
#define APIMATIC_ELECTRONICEQUIPMENTINSURANCE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Franchisee.h"
#import "DeviceType.h"
#import "InsuranceCompany.h"
#import "InsurancePolicyTerm.h"
#import "Province.h"
#import "ShippingType.h"
#import "PostType.h"
#import "InsurancePolicyCondition.h"
#import "InsuranceData.h"


//protocol defined for deserialization of JSON
@protocol ElectronicEquipmentInsurance
@end

@interface ElectronicEquipmentInsurance : JSONModel

/**
* آیا این نوع بیمه نامه، طرح بیمه ای دارد؟
*/
@property BOOL hasPlan;

/**
* لیست فرانشیز های بیمه ی تجهیزات الکترونیک
*/
@property NSArray<Franchisee> * franchisees;

/**
* انواع دستگاه ها
*/
@property NSArray<DeviceType> * deviceTypes;

/**
* برند های دستگاه ها
*/
@property NSArray* deviceBrands;

/**
* مدل های دستگاه ها
*/
@property NSArray* deviceModels;

/**
* شرکت های بیمه ی ارائه دهنده ی بیمه ی تجهیزات الکترونیک
*/
@property NSArray<InsuranceCompany> * insuranceCompanies;

/**
* پوشش های اضافه
*/
@property NSArray* insuranceExtraCoverage;

/**
* دوره های بیمه نامه
*/
@property NSArray<InsurancePolicyTerm> * insurancePolicyTerms;

/**
* لیست استان ها
*/
@property NSArray<Province> * provinces;

/**
* لیست شهر ها
*/
@property NSArray* cities;

/**
* لیست محله ها
*/
@property NSArray* cityRegions;

/**
* روش های دریافت بیمه نامه
*/
@property NSArray<ShippingType> * shippingTypes;

/**
* روش های ارسال بیمه نامه
*/
@property NSArray<PostType> * postTypes;

/**
* شرایط بیمه نامه
*/
@property InsurancePolicyCondition* insurancePolicyCondition;

/**
* اطلاعات بیمه نامه
*/
@property InsuranceData* insuranceData;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif