//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "ElectronicEquipmentInsurance.h"

@implementation ElectronicEquipmentInsurance

/**
* آیا این نوع بیمه نامه، طرح بیمه ای دارد؟
*/
@synthesize hasPlan;

/**
* لیست فرانشیز های بیمه ی تجهیزات الکترونیک
*/
@synthesize franchisees;

/**
* انواع دستگاه ها
*/
@synthesize deviceTypes;

/**
* برند های دستگاه ها
*/
@synthesize deviceBrands;

/**
* مدل های دستگاه ها
*/
@synthesize deviceModels;

/**
* شرکت های بیمه ی ارائه دهنده ی بیمه ی تجهیزات الکترونیک
*/
@synthesize insuranceCompanies;

/**
* پوشش های اضافه
*/
@synthesize insuranceExtraCoverage;

/**
* دوره های بیمه نامه
*/
@synthesize insurancePolicyTerms;

/**
* لیست استان ها
*/
@synthesize provinces;

/**
* لیست شهر ها
*/
@synthesize cities;

/**
* لیست محله ها
*/
@synthesize cityRegions;

/**
* روش های دریافت بیمه نامه
*/
@synthesize shippingTypes;

/**
* روش های ارسال بیمه نامه
*/
@synthesize postTypes;

/**
* شرایط بیمه نامه
*/
@synthesize insurancePolicyCondition;

/**
* اطلاعات بیمه نامه
*/
@synthesize insuranceData;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"hasPlan": @"hasPlan",
        @"franchisees": @"franchisees",
        @"deviceTypes": @"deviceTypes",
        @"deviceBrands": @"deviceBrands",
        @"deviceModels": @"deviceModels",
        @"insuranceCompanies": @"insuranceCompanies",
        @"insuranceExtraCoverage": @"insuranceExtraCoverage",
        @"insurancePolicyTerms": @"insurancePolicyTerms",
        @"provinces": @"provinces",
        @"cities": @"cities",
        @"cityRegions": @"cityRegions",
        @"shippingTypes": @"shippingTypes",
        @"postTypes": @"postTypes",
        @"insurancePolicyCondition": @"insurancePolicyCondition",
        @"insuranceData": @"insuranceData"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end