//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_ELEVATORINSURANCE
#define APIMATIC_ELEVATORINSURANCE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ComboDataModel.h"
#import "ElevatorType.h"
#import "DefectOrganCoverage.h"
#import "DeathCapitalCoverage.h"
#import "FinancialCoverage.h"
#import "MedicalCostCoverage.h"
#import "InsuranceRiskLevel.h"
#import "InsurancePolicyTerm.h"
#import "InsuranceCompany.h"
#import "Province.h"
#import "ShippingType.h"
#import "PostType.h"
#import "InsurancePolicyCondition.h"
#import "InsuranceDataElevatorInsurance.h"


//protocol defined for deserialization of JSON
@protocol ElevatorInsurance
@end

@interface ElevatorInsurance : JSONModel

/**
* TODO: Write general description for this field
*/
@property BOOL hasPlan;

/**
* TODO: Write general description for this field
*/
@property NSArray<ComboDataModel> * buildingUseTypes;

/**
* TODO: Write general description for this field
*/
@property NSArray<ElevatorType> * elevatorTypes;

/**
* TODO: Write general description for this field
*/
@property NSArray<DefectOrganCoverage> * defectOrganCoverage;

/**
* TODO: Write general description for this field
*/
@property NSArray<DeathCapitalCoverage> * deathCapitalCoverage;

/**
* TODO: Write general description for this field
*/
@property NSArray<FinancialCoverage> * financialCoverage;

/**
* TODO: Write general description for this field
*/
@property NSArray<MedicalCostCoverage> * medicalCostCoverage;

/**
* TODO: Write general description for this field
*/
@property NSArray<InsuranceRiskLevel> * insuranceRiskLevels;

/**
* TODO: Write general description for this field
*/
@property NSArray<InsurancePolicyTerm> * insurancePolicyTerms;

/**
* TODO: Write general description for this field
*/
@property NSArray<InsuranceCompany> * insuranceCompanies;

/**
* TODO: Write general description for this field
*/
@property NSArray<Province> * provinces;

/**
* TODO: Write general description for this field
*/
@property NSArray* cities;

/**
* TODO: Write general description for this field
*/
@property NSArray* cityRegions;

/**
* TODO: Write general description for this field
*/
@property NSArray<ShippingType> * shippingTypes;

/**
* TODO: Write general description for this field
*/
@property NSArray<PostType> * postTypes;

/**
* TODO: Write general description for this field
*/
@property InsurancePolicyCondition* insurancePolicyCondition;

/**
* TODO: Write general description for this field
*/
@property InsuranceDataElevatorInsurance* insuranceData;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif