//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_ELEVATORINSURANCEPOLICYFILTER
#define APIMATIC_ELEVATORINSURANCEPOLICYFILTER

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol ElevatorInsurancePolicyFilter
@end

@interface ElevatorInsurancePolicyFilter : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* buildingUseTypeParamId;

/**
* TODO: Write general description for this field
*/
@property NSString* elevatorTypeParamId;

/**
* TODO: Write general description for this field
*/
@property NSString* floors;

/**
* TODO: Write general description for this field
*/
@property NSString* elevatorCapacityCargo;

/**
* TODO: Write general description for this field
*/
@property NSString* elevatorCapacity;

/**
* TODO: Write general description for this field
*/
@property NSString* riskLevelId;

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicyTerms;

/**
* TODO: Write general description for this field
*/
@property NSString* defectOrganCoverageId;

/**
* TODO: Write general description for this field
*/
@property NSString* deathCapitalCoverageId;

/**
* TODO: Write general description for this field
*/
@property NSString* financialCoverageId;

/**
* TODO: Write general description for this field
*/
@property NSString* medicalCostCoverageId;

/**
* TODO: Write general description for this field
*/
@property BOOL ownerCoverage;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceExtraCoverageIds;

/**
* TODO: Write general description for this field
*/
@property NSString* policyTermId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreSubDomainName;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCompanyId;

/**
* TODO: Write general description for this field
*/
@property BOOL isSearchQuery;

/**
* TODO: Write general description for this field
*/
@property NSString* giftCode;

/**
* TODO: Write general description for this field
*/
@property NSString* customerUserId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif