//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "ElevatorInsurancePolicyFilter.h"

@implementation ElevatorInsurancePolicyFilter

/**
* TODO: Write general description for this method
*/
@synthesize buildingUseTypeParamId;

/**
* TODO: Write general description for this method
*/
@synthesize elevatorTypeParamId;

/**
* TODO: Write general description for this method
*/
@synthesize floors;

/**
* TODO: Write general description for this method
*/
@synthesize elevatorCapacityCargo;

/**
* TODO: Write general description for this method
*/
@synthesize elevatorCapacity;

/**
* TODO: Write general description for this method
*/
@synthesize riskLevelId;

/**
* TODO: Write general description for this method
*/
@synthesize insurancePolicyTerms;

/**
* TODO: Write general description for this method
*/
@synthesize defectOrganCoverageId;

/**
* TODO: Write general description for this method
*/
@synthesize deathCapitalCoverageId;

/**
* TODO: Write general description for this method
*/
@synthesize financialCoverageId;

/**
* TODO: Write general description for this method
*/
@synthesize medicalCostCoverageId;

/**
* TODO: Write general description for this method
*/
@synthesize ownerCoverage;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceExtraCoverageIds;

/**
* TODO: Write general description for this method
*/
@synthesize policyTermId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreSubDomainName;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyId;

/**
* TODO: Write general description for this method
*/
@synthesize isSearchQuery;

/**
* TODO: Write general description for this method
*/
@synthesize giftCode;

/**
* TODO: Write general description for this method
*/
@synthesize customerUserId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"buildingUseTypeParamId": @"buildingUseTypeParamId",
        @"elevatorTypeParamId": @"elevatorTypeParamId",
        @"floors": @"floors",
        @"elevatorCapacityCargo": @"elevatorCapacityCargo",
        @"elevatorCapacity": @"elevatorCapacity",
        @"riskLevelId": @"riskLevelId",
        @"insurancePolicyTerms": @"insurancePolicyTerms",
        @"defectOrganCoverageId": @"defectOrganCoverageId",
        @"deathCapitalCoverageId": @"deathCapitalCoverageId",
        @"financialCoverageId": @"financialCoverageId",
        @"medicalCostCoverageId": @"medicalCostCoverageId",
        @"ownerCoverage": @"ownerCoverage",
        @"insuranceExtraCoverageIds": @"insuranceExtraCoverageIds",
        @"policyTermId": @"policyTermId",
        @"insuranceCentreSubDomainName": @"insuranceCentreSubDomainName",
        @"insuranceCentreId": @"insuranceCentreId",
        @"insuranceCompanyId": @"insuranceCompanyId",
        @"isSearchQuery": @"isSearchQuery",
        @"giftCode": @"giftCode",
        @"customerUserId": @"customerUserId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end