//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_ELEVATORINSURANCEPOLICYEXTENDVIEW
#define APIMATIC_ELEVATORINSURANCEPOLICYEXTENDVIEW

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol ElevatorInsurancePolicyExtendView
@end

@interface ElevatorInsurancePolicyExtendView : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* buildingUseTypeParamId;

/**
* TODO: Write general description for this field
*/
@property NSString* elevatorTypeParamId;

/**
* TODO: Write general description for this field
*/
@property NSString* floors;

/**
* TODO: Write general description for this field
*/
@property NSString* elevatorCapacity;

/**
* TODO: Write general description for this field
*/
@property NSString* elevatorCapacityCargo;

/**
* TODO: Write general description for this field
*/
@property NSString* defectOrganCoverageId;

/**
* TODO: Write general description for this field
*/
@property NSString* deathCapitalCoverageId;

/**
* TODO: Write general description for this field
*/
@property NSString* financialCoverageId;

/**
* TODO: Write general description for this field
*/
@property NSString* medicalCostCoverageId;

/**
* TODO: Write general description for this field
*/
@property NSString* riskLevelDiscountRate;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceRiskLevelId;

/**
* TODO: Write general description for this field
*/
@property NSString* discountRate;

/**
* TODO: Write general description for this field
*/
@property NSString* cityId;

/**
* TODO: Write general description for this field
*/
@property NSString* provinceId;

/**
* TODO: Write general description for this field
*/
@property NSString* zipCode;

/**
* TODO: Write general description for this field
*/
@property NSString* addressPlaceBuilding;

/**
* TODO: Write general description for this field
*/
@property BOOL ownerCoverage;

/**
* TODO: Write general description for this field
*/
@property int riskLevelDiscount;

/**
* TODO: Write general description for this field
*/
@property NSString* basePremium;

/**
* TODO: Write general description for this field
*/
@property NSString* allPremium;

/**
* TODO: Write general description for this field
*/
@property int insuranceCompanyDiscountRate;

/**
* TODO: Write general description for this field
*/
@property int insuranceCompanyDiscount;

/**
* TODO: Write general description for this field
*/
@property int insuranceCentreDiscount;

/**
* TODO: Write general description for this field
*/
@property int coupenDiscount;

/**
* TODO: Write general description for this field
*/
@property int allDiscount;

/**
* TODO: Write general description for this field
*/
@property int exchangePremium;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif