//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "ElevatorInsurancePolicyExtendView.h"

@implementation ElevatorInsurancePolicyExtendView

/**
* TODO: Write general description for this method
*/
@synthesize buildingUseTypeParamId;

/**
* TODO: Write general description for this method
*/
@synthesize elevatorTypeParamId;

/**
* TODO: Write general description for this method
*/
@synthesize floors;

/**
* TODO: Write general description for this method
*/
@synthesize elevatorCapacity;

/**
* TODO: Write general description for this method
*/
@synthesize elevatorCapacityCargo;

/**
* TODO: Write general description for this method
*/
@synthesize defectOrganCoverageId;

/**
* TODO: Write general description for this method
*/
@synthesize deathCapitalCoverageId;

/**
* TODO: Write general description for this method
*/
@synthesize financialCoverageId;

/**
* TODO: Write general description for this method
*/
@synthesize medicalCostCoverageId;

/**
* TODO: Write general description for this method
*/
@synthesize riskLevelDiscountRate;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceRiskLevelId;

/**
* TODO: Write general description for this method
*/
@synthesize discountRate;

/**
* TODO: Write general description for this method
*/
@synthesize cityId;

/**
* TODO: Write general description for this method
*/
@synthesize provinceId;

/**
* TODO: Write general description for this method
*/
@synthesize zipCode;

/**
* TODO: Write general description for this method
*/
@synthesize addressPlaceBuilding;

/**
* TODO: Write general description for this method
*/
@synthesize ownerCoverage;

/**
* TODO: Write general description for this method
*/
@synthesize riskLevelDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize basePremium;

/**
* TODO: Write general description for this method
*/
@synthesize allPremium;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyDiscountRate;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize coupenDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize allDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize exchangePremium;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"buildingUseTypeParamId": @"buildingUseTypeParamId",
        @"elevatorTypeParamId": @"elevatorTypeParamId",
        @"floors": @"floors",
        @"elevatorCapacity": @"elevatorCapacity",
        @"elevatorCapacityCargo": @"elevatorCapacityCargo",
        @"defectOrganCoverageId": @"defectOrganCoverageId",
        @"deathCapitalCoverageId": @"deathCapitalCoverageId",
        @"financialCoverageId": @"financialCoverageId",
        @"medicalCostCoverageId": @"medicalCostCoverageId",
        @"riskLevelDiscountRate": @"riskLevelDiscountRate",
        @"insuranceRiskLevelId": @"insuranceRiskLevelId",
        @"discountRate": @"discountRate",
        @"cityId": @"cityId",
        @"provinceId": @"provinceId",
        @"zipCode": @"zipCode",
        @"addressPlaceBuilding": @"addressPlaceBuilding",
        @"ownerCoverage": @"ownerCoverage",
        @"riskLevelDiscount": @"riskLevelDiscount",
        @"basePremium": @"basePremium",
        @"allPremium": @"allPremium",
        @"insuranceCompanyDiscountRate": @"insuranceCompanyDiscountRate",
        @"insuranceCompanyDiscount": @"insuranceCompanyDiscount",
        @"insuranceCentreDiscount": @"insuranceCentreDiscount",
        @"coupenDiscount": @"coupenDiscount",
        @"allDiscount": @"allDiscount",
        @"exchangePremium": @"exchangePremium"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end