//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Exception.h"

@implementation Exception

/**
* TODO: Write general description for this method
*/
@synthesize dateTime;

/**
* TODO: Write general description for this method
*/
@synthesize message;

/**
* TODO: Write general description for this method
*/
@synthesize helpLink;

/**
* TODO: Write general description for this method
*/
@synthesize source;

/**
* TODO: Write general description for this method
*/
@synthesize stackTrace;

/**
* TODO: Write general description for this method
*/
@synthesize targetSite;

/**
* TODO: Write general description for this method
*/
@synthesize errorLine;

/**
* TODO: Write general description for this method
*/
@synthesize exceptionType;

/**
* TODO: Write general description for this method
*/
@synthesize exceptionUrl;

/**
* TODO: Write general description for this method
*/
@synthesize innerException;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"dateTime": @"dateTime",
        @"message": @"message",
        @"helpLink": @"helpLink",
        @"source": @"source",
        @"stackTrace": @"stackTrace",
        @"targetSite": @"targetSite",
        @"errorLine": @"errorLine",
        @"exceptionType": @"exceptionType",
        @"exceptionUrl": @"exceptionUrl",
        @"innerException": @"innerException"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end