//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "FireInsurancePolicyFilter.h"

@implementation FireInsurancePolicyFilter

/**
* TODO: Write general description for this method
*/
@synthesize insurancePolicyType;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceExtraCoverageIds;

/**
* TODO: Write general description for this method
*/
@synthesize valuePerSquareMeterCoverageRateId;

/**
* TODO: Write general description for this method
*/
@synthesize valueOfAppliancesFurnishing;

/**
* TODO: Write general description for this method
*/
@synthesize cityId;

/**
* TODO: Write general description for this method
*/
@synthesize skeletonTypeId;

/**
* TODO: Write general description for this method
*/
@synthesize buildingTypeId;

/**
* TODO: Write general description for this method
*/
@synthesize buildingArea;

/**
* TODO: Write general description for this method
*/
@synthesize onlyAppliancesFurnishings;

/**
* TODO: Write general description for this method
*/
@synthesize policyTermId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreSubDomainName;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyId;

/**
* TODO: Write general description for this method
*/
@synthesize giftCode;

/**
* TODO: Write general description for this method
*/
@synthesize customerUserId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"insurancePolicyType": @"insurancePolicyType",
        @"insuranceExtraCoverageIds": @"insuranceExtraCoverageIds",
        @"valuePerSquareMeterCoverageRateId": @"valuePerSquareMeterCoverageRateId",
        @"valueOfAppliancesFurnishing": @"valueOfAppliancesFurnishing",
        @"cityId": @"cityId",
        @"skeletonTypeId": @"skeletonTypeId",
        @"buildingTypeId": @"buildingTypeId",
        @"buildingArea": @"buildingArea",
        @"onlyAppliancesFurnishings": @"onlyAppliancesFurnishings",
        @"policyTermId": @"policyTermId",
        @"insuranceCentreSubDomainName": @"insuranceCentreSubDomainName",
        @"insuranceCentreId": @"insuranceCentreId",
        @"insuranceCompanyId": @"insuranceCompanyId",
        @"giftCode": @"giftCode",
        @"customerUserId": @"customerUserId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end