//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_FIREINSURANCEPOLICYFILTER
#define APIMATIC_FIREINSURANCEPOLICYFILTER

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol FireInsurancePolicyFilter
@end

@interface FireInsurancePolicyFilter : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicyType;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceExtraCoverageIds;

/**
* TODO: Write general description for this field
*/
@property NSString* valuePerSquareMeterCoverageRateId;

/**
* TODO: Write general description for this field
*/
@property NSString* valueOfAppliancesFurnishing;

/**
* TODO: Write general description for this field
*/
@property NSString* cityId;

/**
* TODO: Write general description for this field
*/
@property NSString* skeletonTypeId;

/**
* TODO: Write general description for this field
*/
@property int buildingTypeId;

/**
* TODO: Write general description for this field
*/
@property NSString* buildingArea;

/**
* TODO: Write general description for this field
*/
@property NSString* onlyAppliancesFurnishings;

/**
* TODO: Write general description for this field
*/
@property NSString* policyTermId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreSubDomainName;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCompanyId;

/**
* TODO: Write general description for this field
*/
@property NSString* giftCode;

/**
* TODO: Write general description for this field
*/
@property NSString* customerUserId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif