//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_FIREINSURANCEPOLICYEXTENDVIEW
#define APIMATIC_FIREINSURANCEPOLICYEXTENDVIEW

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol FireInsurancePolicyExtendView
@end

@interface FireInsurancePolicyExtendView : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* buildingTypeParamId;

/**
* TODO: Write general description for this field
*/
@property NSString* skeletonTypeBuildingParamId;

/**
* TODO: Write general description for this field
*/
@property NSString* buildingUseTypeParamId;

/**
* TODO: Write general description for this field
*/
@property NSString* unitCount;

/**
* TODO: Write general description for this field
*/
@property int everySquareMeterCoverageRateId;

/**
* TODO: Write general description for this field
*/
@property NSString* cityId;

/**
* TODO: Write general description for this field
*/
@property NSString* provinceId;

/**
* TODO: Write general description for this field
*/
@property NSString* buildingArea;

/**
* TODO: Write general description for this field
*/
@property NSString* valueOfAppliancesFurnishing;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCoverageIds;

/**
* TODO: Write general description for this field
*/
@property BOOL onlyAppliancesFurnishings;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCoveragePrice;

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicyCommitmentCeiling;

/**
* TODO: Write general description for this field
*/
@property NSString* valuePerSquareMeterRate;

/**
* TODO: Write general description for this field
*/
@property NSString* buildYear;

/**
* TODO: Write general description for this field
*/
@property NSString* zipCode;

/**
* TODO: Write general description for this field
*/
@property NSString* addressPlaceBuilding;

/**
* TODO: Write general description for this field
*/
@property int riskLevelDiscount;

/**
* TODO: Write general description for this field
*/
@property NSString* basePremium;

/**
* TODO: Write general description for this field
*/
@property NSString* allPremium;

/**
* TODO: Write general description for this field
*/
@property int insuranceCompanyDiscountRate;

/**
* TODO: Write general description for this field
*/
@property int insuranceCompanyDiscount;

/**
* TODO: Write general description for this field
*/
@property int insuranceCentreDiscount;

/**
* TODO: Write general description for this field
*/
@property int coupenDiscount;

/**
* TODO: Write general description for this field
*/
@property int allDiscount;

/**
* TODO: Write general description for this field
*/
@property int exchangePremium;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif