//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "FireInsurancePolicyExtendView.h"

@implementation FireInsurancePolicyExtendView

/**
* TODO: Write general description for this method
*/
@synthesize buildingTypeParamId;

/**
* TODO: Write general description for this method
*/
@synthesize skeletonTypeBuildingParamId;

/**
* TODO: Write general description for this method
*/
@synthesize buildingUseTypeParamId;

/**
* TODO: Write general description for this method
*/
@synthesize unitCount;

/**
* TODO: Write general description for this method
*/
@synthesize everySquareMeterCoverageRateId;

/**
* TODO: Write general description for this method
*/
@synthesize cityId;

/**
* TODO: Write general description for this method
*/
@synthesize provinceId;

/**
* TODO: Write general description for this method
*/
@synthesize buildingArea;

/**
* TODO: Write general description for this method
*/
@synthesize valueOfAppliancesFurnishing;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCoverageIds;

/**
* TODO: Write general description for this method
*/
@synthesize onlyAppliancesFurnishings;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCoveragePrice;

/**
* TODO: Write general description for this method
*/
@synthesize insurancePolicyCommitmentCeiling;

/**
* TODO: Write general description for this method
*/
@synthesize valuePerSquareMeterRate;

/**
* TODO: Write general description for this method
*/
@synthesize buildYear;

/**
* TODO: Write general description for this method
*/
@synthesize zipCode;

/**
* TODO: Write general description for this method
*/
@synthesize addressPlaceBuilding;

/**
* TODO: Write general description for this method
*/
@synthesize riskLevelDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize basePremium;

/**
* TODO: Write general description for this method
*/
@synthesize allPremium;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyDiscountRate;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize coupenDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize allDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize exchangePremium;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"buildingTypeParamId": @"buildingTypeParamId",
        @"skeletonTypeBuildingParamId": @"skeletonTypeBuildingParamId",
        @"buildingUseTypeParamId": @"buildingUseTypeParamId",
        @"unitCount": @"unitCount",
        @"everySquareMeterCoverageRateId": @"everySquareMeterCoverageRateId",
        @"cityId": @"cityId",
        @"provinceId": @"provinceId",
        @"buildingArea": @"buildingArea",
        @"valueOfAppliancesFurnishing": @"valueOfAppliancesFurnishing",
        @"_InsuranceCoverageIds": @"insuranceCoverageIds",
        @"onlyAppliancesFurnishings": @"onlyAppliancesFurnishings",
        @"insuranceCoveragePrice": @"insuranceCoveragePrice",
        @"insurancePolicyCommitmentCeiling": @"insurancePolicyCommitmentCeiling",
        @"valuePerSquareMeterRate": @"valuePerSquareMeterRate",
        @"buildYear": @"buildYear",
        @"zipCode": @"zipCode",
        @"addressPlaceBuilding": @"addressPlaceBuilding",
        @"riskLevelDiscount": @"riskLevelDiscount",
        @"basePremium": @"basePremium",
        @"allPremium": @"allPremium",
        @"insuranceCompanyDiscountRate": @"insuranceCompanyDiscountRate",
        @"insuranceCompanyDiscount": @"insuranceCompanyDiscount",
        @"insuranceCentreDiscount": @"insuranceCentreDiscount",
        @"coupenDiscount": @"coupenDiscount",
        @"allDiscount": @"allDiscount",
        @"exchangePremium": @"exchangePremium"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end