//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "GalleryDetail.h"

@implementation GalleryDetail

/**
* TODO: Write general description for this method
*/
@synthesize galleryId;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaFileId;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaFileUrl;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"galleryId": @"galleryId",
        @"metaMediaFileId": @"metaMediaFileId",
        @"metaMediaFileUrl": @"metaMediaFileUrl"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end