//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_GALLERYDETAIL
#define APIMATIC_GALLERYDETAIL

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol GalleryDetail
@end

@interface GalleryDetail : JSONModel

/**
* TODO: Write general description for this field
*/
@property int galleryId;

/**
* TODO: Write general description for this field
*/
@property int metaMediaFileId;

/**
* TODO: Write general description for this field
*/
@property NSString* metaMediaFileUrl;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif