//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_GETACCESSTOKENUSERINFO
#define APIMATIC_GETACCESSTOKENUSERINFO

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol GetAccessTokenUserInfo
@end

@interface GetAccessTokenUserInfo : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* mid;

/**
* TODO: Write general description for this field
*/
@property NSString* accessToken;

/**
* TODO: Write general description for this field
*/
@property NSString* expiresIn;

/**
* TODO: Write general description for this field
*/
@property NSString* refreshToken;

/**
* TODO: Write general description for this field
*/
@property NSString* error;

/**
* TODO: Write general description for this field
*/
@property NSString* userName;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreName;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreLogo;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreFavicon;

/**
* TODO: Write general description for this field
*/
@property BOOL licensed;

/**
* TODO: Write general description for this field
*/
@property NSString* email;

/**
* TODO: Write general description for this field
*/
@property int insuranceCentreType;

/**
* TODO: Write general description for this field
*/
@property NSString* avatarUrl;

/**
* TODO: Write general description for this field
*/
@property NSString* aliasName;

/**
* TODO: Write general description for this field
*/
@property int userGroup;

/**
* TODO: Write general description for this field
*/
@property NSString* userGroupTitle;

/**
* TODO: Write general description for this field
*/
@property NSArray* roleIds;

/**
* TODO: Write general description for this field
*/
@property NSString* roleTitles;

/**
* TODO: Write general description for this field
*/
@property BOOL unlimitedAccount;

/**
* TODO: Write general description for this field
*/
@property NSString* rolePermissions;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif