//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "GetAccessTokenUserInfo.h"

@implementation GetAccessTokenUserInfo

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize accessToken;

/**
* TODO: Write general description for this method
*/
@synthesize expiresIn;

/**
* TODO: Write general description for this method
*/
@synthesize refreshToken;

/**
* TODO: Write general description for this method
*/
@synthesize error;

/**
* TODO: Write general description for this method
*/
@synthesize userName;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreName;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreLogo;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreFavicon;

/**
* TODO: Write general description for this method
*/
@synthesize licensed;

/**
* TODO: Write general description for this method
*/
@synthesize email;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreType;

/**
* TODO: Write general description for this method
*/
@synthesize avatarUrl;

/**
* TODO: Write general description for this method
*/
@synthesize aliasName;

/**
* TODO: Write general description for this method
*/
@synthesize userGroup;

/**
* TODO: Write general description for this method
*/
@synthesize userGroupTitle;

/**
* TODO: Write general description for this method
*/
@synthesize roleIds;

/**
* TODO: Write general description for this method
*/
@synthesize roleTitles;

/**
* TODO: Write general description for this method
*/
@synthesize unlimitedAccount;

/**
* TODO: Write general description for this method
*/
@synthesize rolePermissions;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"access_token": @"accessToken",
        @"expires_in": @"expiresIn",
        @"refresh_token": @"refreshToken",
        @"error": @"error",
        @"userName": @"userName",
        @"insuranceCentreName": @"insuranceCentreName",
        @"insuranceCentreLogo": @"insuranceCentreLogo",
        @"insuranceCentreFavicon": @"insuranceCentreFavicon",
        @"licensed": @"licensed",
        @"email": @"email",
        @"insuranceCentreType": @"insuranceCentreType",
        @"avatarUrl": @"avatarUrl",
        @"aliasName": @"aliasName",
        @"userGroup": @"userGroup",
        @"userGroupTitle": @"userGroupTitle",
        @"roleIds": @"roleIds",
        @"roleTitles": @"roleTitles",
        @"unlimitedAccount": @"unlimitedAccount",
        @"rolePermissions": @"rolePermissions"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end