//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_IMAGEALBUM
#define APIMATIC_IMAGEALBUM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "PopupImageGalleryie.h"
#import "GalleryDetail.h"


//protocol defined for deserialization of JSON
@protocol ImageAlbum
@end

@interface ImageAlbum : JSONModel

/**
* TODO: Write general description for this field
*/
@property int mid;

/**
* TODO: Write general description for this field
*/
@property int galleryType;

/**
* TODO: Write general description for this field
*/
@property NSString* title;

/**
* TODO: Write general description for this field
*/
@property NSString* alt;

/**
* TODO: Write general description for this field
*/
@property NSString* description;

/**
* TODO: Write general description for this field
*/
@property BOOL isActive;

/**
* TODO: Write general description for this field
*/
@property BOOL isMain;

/**
* TODO: Write general description for this field
*/
@property BOOL isAttachFile;

/**
* TODO: Write general description for this field
*/
@property NSString* sortPriority;

/**
* TODO: Write general description for this field
*/
@property NSString* createOnPersianDate;

/**
* TODO: Write general description for this field
*/
@property int metaMediaFileId;

/**
* TODO: Write general description for this field
*/
@property NSString* metaMediaFileUrl;

/**
* TODO: Write general description for this field
*/
@property NSString* metaMediaFileThumbnailUrl;

/**
* TODO: Write general description for this field
*/
@property NSArray<PopupImageGalleryie> * popupImageGalleryies;

/**
* TODO: Write general description for this field
*/
@property NSArray<GalleryDetail> * galleryDetails;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif