//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_INSURANCEPOLICYTRACKING
#define APIMATIC_INSURANCEPOLICYTRACKING

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol InsurancePolicyTracking
@end

@interface InsurancePolicyTracking : JSONModel

/**
* TODO: Write general description for this field
*/
@property int mid;

/**
* TODO: Write general description for this field
*/
@property NSString* aliasName;

/**
* TODO: Write general description for this field
*/
@property NSString* status;

/**
* TODO: Write general description for this field
*/
@property NSString* createOnPersianDate;

/**
* TODO: Write general description for this field
*/
@property NSString* centerName;

/**
* TODO: Write general description for this field
*/
@property int insurancePolicyType;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceType;

/**
* TODO: Write general description for this field
*/
@property int price;

/**
* TODO: Write general description for this field
*/
@property NSString* paymented;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif