//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "InsuranceCentrePolicyTypes.h"

@implementation InsuranceCentrePolicyTypes

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize title;

/**
* TODO: Write general description for this method
*/
@synthesize iconImage;

/**
* TODO: Write general description for this method
*/
@synthesize isActive;

/**
* TODO: Write general description for this method
*/
@synthesize routingUrl;

/**
* TODO: Write general description for this method
*/
@synthesize displayPriority;

/**
* TODO: Write general description for this method
*/
@synthesize iconPosition;

/**
* TODO: Write general description for this method
*/
@synthesize generalTerms;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"title": @"title",
        @"iconImage": @"iconImage",
        @"isActive": @"isActive",
        @"routingUrl": @"routingUrl",
        @"displayPriority": @"displayPriority",
        @"iconPosition": @"iconPosition",
        @"generalTerms": @"generalTerms"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end