//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "InsurancePolicyCondition.h"

@implementation InsurancePolicyCondition

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* شناسه ی مرکز بیمه
*/
@synthesize insuranceCentreId;

/**
* شناسه ی نوع بیمه نامه ی شرکت بیمه
*/
@synthesize insuranceCompanyPolicyTypeId;

/**
* الویت نمایش
*/
@synthesize displayPriority;

/**
* امکان صدور بیمه نامه
*/
@synthesize issueInsurance;

/**
* ارزیابی خسارت
*/
@synthesize damageAssessment;

/**
* پرداخت نقدی
*/
@synthesize cashPayment;

/**
* پرداخت اقساطی
*/
@synthesize installmentsPayment;

/**
* درصدر پیش پرداخت
*/
@synthesize prepaymentPercent;

/**
* تعداد اقساط از
*/
@synthesize countInstallmentFrom;

/**
* تعداد اقساط تا
*/
@synthesize countInstallmentTo;

/**
* روش فروش
*/
@synthesize paymentMethods;

/**
* پروموشن
*/
@synthesize promotion;

/**
* وضعیت فعال
*/
@synthesize isActive;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"insuranceCentreId": @"insuranceCentreId",
        @"insuranceCompanyPolicyTypeId": @"insuranceCompanyPolicyTypeId",
        @"displayPriority": @"displayPriority",
        @"issueInsurance": @"issueInsurance",
        @"damageAssessment": @"damageAssessment",
        @"cashPayment": @"cashPayment",
        @"installmentsPayment": @"installmentsPayment",
        @"prepaymentPercent": @"prepaymentPercent",
        @"countInstallmentFrom": @"countInstallmentFrom",
        @"countInstallmentTo": @"countInstallmentTo",
        @"paymentMethods": @"paymentMethods",
        @"promotion": @"promotion",
        @"isActive": @"isActive"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end