//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_INSURANCEDATALIABILITYDOCTORINSURANCE
#define APIMATIC_INSURANCEDATALIABILITYDOCTORINSURANCE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "LiabilityDoctorInsurancePolicyExtendView.h"
#import "LiabilityDoctorInsurancePolicyFilter.h"


//protocol defined for deserialization of JSON
@protocol InsuranceDataLiabilityDoctorInsurance
@end

@interface InsuranceDataLiabilityDoctorInsurance : JSONModel

/**
* شرایط اضافه ی بیمه نامه
*/
@property LiabilityDoctorInsurancePolicyExtendView* liabilityDoctorInsurancePolicyExtendView;

/**
* فیلتر های بیمه نامه
*/
@property LiabilityDoctorInsurancePolicyFilter* liabilityDoctorInsurancePolicyFilter;

/**
* TODO: Write general description for this field
*/
@property int mid;

/**
* بیمه نامه تغییر کرده؟
*/
@property BOOL selectedInsurancePolicyHasBeenChanged;

/**
* پرداخت شده؟
*/
@property BOOL isPaymented;

/**
* قابل پرداخت؟
*/
@property NSString* payable;

/**
* پرداخت شده؟
*/
@property NSString* paymented;

/**
* TODO: Write general description for this field
*/
@property NSString* conflict;

/**
* TODO: Write general description for this field
*/
@property BOOL hasConflictDocument;

/**
* قیمت پایه
*/
@property NSString* initialPrice;

/**
* قیمت نهایی
*/
@property NSString* finalPrice;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCompanyName;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreName;

/**
* TODO: Write general description for this field
*/
@property BOOL isInsuranceCentreAdmin;

/**
* TODO: Write general description for this field
*/
@property NSArray* insurancePolicyPaymentDocuments;

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicyConflict;

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicyCondition;

/**
* TODO: Write general description for this field
*/
@property NSString* person;

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicy;

/**
* TODO: Write general description for this field
*/
@property NSString* shoppingCard;

/**
* TODO: Write general description for this field
*/
@property NSString* shoppingCardPostalPacket;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif