//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_INSURANCEDATAFIREINSURANCE
#define APIMATIC_INSURANCEDATAFIREINSURANCE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "FireInsurancePolicyExtendView.h"
#import "FireInsurancePolicyFilter.h"


//protocol defined for deserialization of JSON
@protocol InsuranceDataFireInsurance
@end

@interface InsuranceDataFireInsurance : JSONModel

/**
* TODO: Write general description for this field
*/
@property int insurancePolicyTypeVelue;

/**
* TODO: Write general description for this field
*/
@property FireInsurancePolicyExtendView* fireInsurancePolicyExtendView;

/**
* TODO: Write general description for this field
*/
@property FireInsurancePolicyFilter* fireInsurancePolicyFilter;

/**
* TODO: Write general description for this field
*/
@property int mid;

/**
* TODO: Write general description for this field
*/
@property BOOL selectedInsurancePolicyHasBeenChanged;

/**
* TODO: Write general description for this field
*/
@property BOOL isPaymented;

/**
* TODO: Write general description for this field
*/
@property NSString* payable;

/**
* TODO: Write general description for this field
*/
@property NSString* paymented;

/**
* TODO: Write general description for this field
*/
@property NSString* conflict;

/**
* TODO: Write general description for this field
*/
@property BOOL hasConflictDocument;

/**
* TODO: Write general description for this field
*/
@property NSString* initialPrice;

/**
* TODO: Write general description for this field
*/
@property NSString* finalPrice;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCompanyName;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreName;

/**
* TODO: Write general description for this field
*/
@property BOOL isInsuranceCentreAdmin;

/**
* TODO: Write general description for this field
*/
@property NSArray* insurancePolicyPaymentDocuments;

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicyConflict;

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicyCondition;

/**
* TODO: Write general description for this field
*/
@property NSString* person;

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicy;

/**
* TODO: Write general description for this field
*/
@property NSString* shoppingCard;

/**
* TODO: Write general description for this field
*/
@property NSString* shoppingCardPostalPacket;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif