//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_INSURANCECENTREPORTAL
#define APIMATIC_INSURANCECENTREPORTAL

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol InsuranceCentrePortal
@end

@interface InsuranceCentrePortal : JSONModel

/**
* TODO: Write general description for this field
*/
@property int insuranceCentreId;

/**
* TODO: Write general description for this field
*/
@property NSString* centreName;

/**
* TODO: Write general description for this field
*/
@property NSString* subDomainName;

/**
* TODO: Write general description for this field
*/
@property NSString* title;

/**
* TODO: Write general description for this field
*/
@property NSString* subTitle;

/**
* TODO: Write general description for this field
*/
@property NSString* contactUs;

/**
* TODO: Write general description for this field
*/
@property NSString* aboutUs;

/**
* TODO: Write general description for this field
*/
@property NSString* ourService;

/**
* TODO: Write general description for this field
*/
@property NSString* termsConditions;

/**
* TODO: Write general description for this field
*/
@property NSString* mcopyright;

/**
* TODO: Write general description for this field
*/
@property NSString* headerTitle;

/**
* TODO: Write general description for this field
*/
@property NSString* headerBody;

/**
* TODO: Write general description for this field
*/
@property NSString* footerColor;

/**
* TODO: Write general description for this field
*/
@property NSString* backgroundColor;

/**
* TODO: Write general description for this field
*/
@property BOOL licensed;

/**
* TODO: Write general description for this field
*/
@property NSString* defaultLogo;

/**
* TODO: Write general description for this field
*/
@property NSString* titleColor;

/**
* TODO: Write general description for this field
*/
@property NSString* subTitleColor;

/**
* TODO: Write general description for this field
*/
@property NSString* eTrustSymbol;

/**
* TODO: Write general description for this field
*/
@property NSString* digitalMediaOrganizerSymbol;

/**
* TODO: Write general description for this field
*/
@property NSString* googlePlus;

/**
* TODO: Write general description for this field
*/
@property NSString* telegram;

/**
* TODO: Write general description for this field
*/
@property NSString* instagram;

/**
* TODO: Write general description for this field
*/
@property NSString* faceBook;

/**
* TODO: Write general description for this field
*/
@property NSString* twitter;

/**
* TODO: Write general description for this field
*/
@property NSString* saturdayToWednesdayFromHour;

/**
* TODO: Write general description for this field
*/
@property NSString* saturdayToWednesdayToHour;

/**
* TODO: Write general description for this field
*/
@property NSString* thursdayFromHour;

/**
* TODO: Write general description for this field
*/
@property NSString* thursdayToHour;

/**
* TODO: Write general description for this field
*/
@property NSString* fridayFromHour;

/**
* TODO: Write general description for this field
*/
@property NSString* fridayToHour;

/**
* TODO: Write general description for this field
*/
@property int metaMediaFileHeaderId;

/**
* TODO: Write general description for this field
*/
@property NSString* metaMediaFileHeaderUrl;

/**
* TODO: Write general description for this field
*/
@property int metaMediaFileLogoId;

/**
* TODO: Write general description for this field
*/
@property NSString* metaMediaFileLogoUrl;

/**
* TODO: Write general description for this field
*/
@property int metaMediaFileFaviconId;

/**
* TODO: Write general description for this field
*/
@property NSString* metaMediaFileFaviconUrl;

/**
* TODO: Write general description for this field
*/
@property NSString* metaMediaFileFooterId;

/**
* TODO: Write general description for this field
*/
@property NSString* metaMediaFileFooterUrl;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif