//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_LIABILITYDOCTORINSURANCE
#define APIMATIC_LIABILITYDOCTORINSURANCE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ActivityArea.h"
#import "Expertise.h"
#import "CommitmentCeiling.h"
#import "InsuranceCompany.h"
#import "InsuranceRiskLevel.h"
#import "InsurancePolicyTerm.h"
#import "Province.h"
#import "ShippingType.h"
#import "PostType.h"
#import "InsurancePolicyCondition.h"
#import "InsuranceDataLiabilityDoctorInsurance.h"


//protocol defined for deserialization of JSON
@protocol LiabilityDoctorInsurance
@end

@interface LiabilityDoctorInsurance : JSONModel

/**
* آیا طرح بیمه ای فعالی دارد؟
*/
@property BOOL hasPlan;

/**
* حوزه ی فعالیت
*/
@property NSArray<ActivityArea> * activityArea;

/**
* لیست تخصص ها
*/
@property NSArray<Expertise> * expertises;

/**
* لیست سقف تعهد
*/
@property NSArray<CommitmentCeiling> * commitmentCeilings;

/**
* مبلغ تعهد
*/
@property int physicalCommitment;

/**
* لیست شرکت های بیمه
*/
@property NSArray<InsuranceCompany> * insuranceCompanies;

/**
* تخفیف های بیمه ای
*/
@property NSArray<InsuranceRiskLevel> * insuranceRiskLevels;

/**
* دوره های بیمه ای
*/
@property NSArray<InsurancePolicyTerm> * insurancePolicyTerms;

/**
* لیست استان ها
*/
@property NSArray<Province> * provinces;

/**
* لیست شهر ها
*/
@property NSArray* cities;

/**
* لیست مناطق شهر
*/
@property NSArray* cityRegions;

/**
* نحوه ی ارسال
*/
@property NSArray<ShippingType> * shippingTypes;

/**
* روش های پستی
*/
@property NSArray<PostType> * postTypes;

/**
* شرایط بیمه نامه
*/
@property InsurancePolicyCondition* insurancePolicyCondition;

/**
* اطلاعات بیمه نامه
*/
@property InsuranceDataLiabilityDoctorInsurance* insuranceData;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif