//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "LiabilityDoctorInsurancePolicyFilter.h"

@implementation LiabilityDoctorInsurancePolicyFilter

/**
* TODO: Write general description for this method
*/
@synthesize expertiseParamId;

/**
* TODO: Write general description for this method
*/
@synthesize isResident;

/**
* TODO: Write general description for this method
*/
@synthesize isStudent;

/**
* TODO: Write general description for this method
*/
@synthesize riskLevelId;

/**
* TODO: Write general description for this method
*/
@synthesize activityAreaParamId;

/**
* TODO: Write general description for this method
*/
@synthesize commitmentCeilingParamId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceExtraCoverageIds;

/**
* TODO: Write general description for this method
*/
@synthesize policyTermId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreSubDomainName;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyId;

/**
* TODO: Write general description for this method
*/
@synthesize isSearchQuery;

/**
* TODO: Write general description for this method
*/
@synthesize giftCode;

/**
* TODO: Write general description for this method
*/
@synthesize customerUserId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"expertiseParamId": @"expertiseParamId",
        @"isResident": @"isResident",
        @"isStudent": @"isStudent",
        @"riskLevelId": @"riskLevelId",
        @"activityAreaParamId": @"activityAreaParamId",
        @"commitmentCeilingParamId": @"commitmentCeilingParamId",
        @"insuranceExtraCoverageIds": @"insuranceExtraCoverageIds",
        @"policyTermId": @"policyTermId",
        @"insuranceCentreSubDomainName": @"insuranceCentreSubDomainName",
        @"insuranceCentreId": @"insuranceCentreId",
        @"insuranceCompanyId": @"insuranceCompanyId",
        @"isSearchQuery": @"isSearchQuery",
        @"giftCode": @"giftCode",
        @"customerUserId": @"customerUserId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end