//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "LiabilityDoctorInsurancePolicyExtendView.h"

@implementation LiabilityDoctorInsurancePolicyExtendView

/**
* شناسه ی نرخ پوشش پزشکی
*/
@synthesize liabilityDoctorCoverageRateId;

/**
* شناسه ی دوره های فعالیت
*/
@synthesize activityAreaParamId;

/**
* شاسه ی تخصص
*/
@synthesize expertiseParamId;

/**
* شناسه ی سقف تعهد
*/
@synthesize commitmentCeilingParamId;

/**
* شناسه ی تخفیف
*/
@synthesize insuranceRiskLevelId;

/**
* تاریخ پایان بیمه نامه
*/
@synthesize currentInsuranceDeadline;

/**
* نرخ تخفیف پوشش
*/
@synthesize riskLevelDiscountRate;

/**
* خسارت جانی
*/
@synthesize physicalCommitment;

/**
* نرخ تخفیف
*/
@synthesize discountRate;

/**
* پوشش پایه
*/
@synthesize basePremium;

/**
* پوشش ها
*/
@synthesize allPremium;

/**
* اطلاعات اضافه
*/
@synthesize allExtraValues;

/**
* نرخ تخفیف شرکت بیمه
*/
@synthesize insuranceCompanyDiscountRate;

/**
* لیست تخفیفات
*/
@synthesize allDiscount;

/**
* نوع ارز حق بیمه
*/
@synthesize exchangePremium;

/**
* نام پزشک
*/
@synthesize doctorName;

/**
* شماره ی نظام پزشکی
*/
@synthesize medicalSystemNO;

/**
* آدرس
*/
@synthesize address;

/**
* آیا رزیدنت است؟
*/
@synthesize isResident;

/**
* آیا دانشجو است؟
*/
@synthesize isStudent;

/**
* دارای مطب؟
*/
@synthesize hasClinic;

/**
* شناسه ی گواهی نظام پزشکی
*/
@synthesize metaMediaMedicalSystemLicenseId;

/**
* آدرس گواهی نظام پزشکی
*/
@synthesize metaMediaMedicalSystemLicenseUrl;

/**
* شناسه ی کارت ملی
*/
@synthesize metaMediaNationalCardId;

/**
* آدرس کارت ملی
*/
@synthesize metaMediaNationalCardUrl;

/**
* شناسه ی بیمه نامه ی کنونی
*/
@synthesize metaMediaCurrentInsurancePolicyId;

/**
* آدرس بیمه نامه ی کنونی
*/
@synthesize metaMediaCurrentInsurancePolicyUrl;

/**
* شناسه ی دوره های بیمه نامه
*/
@synthesize activityAreaEnumName;

/**
* نام دوره ی بیمه نامه
*/
@synthesize activityAreaTitle;

/**
* نام تخصص
*/
@synthesize expertiseTitle;

/**
* وضعیت پزشک
*/
@synthesize docterStatusTitle;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"liabilityDoctorCoverageRateId": @"liabilityDoctorCoverageRateId",
        @"activityAreaParamId": @"activityAreaParamId",
        @"expertiseParamId": @"expertiseParamId",
        @"commitmentCeilingParamId": @"commitmentCeilingParamId",
        @"insuranceRiskLevelId": @"insuranceRiskLevelId",
        @"currentInsuranceDeadline": @"currentInsuranceDeadline",
        @"riskLevelDiscountRate": @"riskLevelDiscountRate",
        @"physicalCommitment": @"physicalCommitment",
        @"discountRate": @"discountRate",
        @"basePremium": @"basePremium",
        @"allPremium": @"allPremium",
        @"allExtraValues": @"allExtraValues",
        @"insuranceCompanyDiscountRate": @"insuranceCompanyDiscountRate",
        @"allDiscount": @"allDiscount",
        @"exchangePremium": @"exchangePremium",
        @"doctorName": @"doctorName",
        @"medicalSystemNO": @"medicalSystemNO",
        @"address": @"address",
        @"isResident": @"isResident",
        @"isStudent": @"isStudent",
        @"hasClinic": @"hasClinic",
        @"metaMediaMedicalSystemLicenseId": @"metaMediaMedicalSystemLicenseId",
        @"metaMediaMedicalSystemLicenseUrl": @"metaMediaMedicalSystemLicenseUrl",
        @"metaMediaNationalCardId": @"metaMediaNationalCardId",
        @"metaMediaNationalCardUrl": @"metaMediaNationalCardUrl",
        @"metaMediaCurrentInsurancePolicyId": @"metaMediaCurrentInsurancePolicyId",
        @"metaMediaCurrentInsurancePolicyUrl": @"metaMediaCurrentInsurancePolicyUrl",
        @"activityAreaEnumName": @"activityAreaEnumName",
        @"activityAreaTitle": @"activityAreaTitle",
        @"expertiseTitle": @"expertiseTitle",
        @"docterStatusTitle": @"docterStatusTitle"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end