//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_LIABILITYDOCTORINSURANCEPOLICYEXTENDVIEW
#define APIMATIC_LIABILITYDOCTORINSURANCEPOLICYEXTENDVIEW

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol LiabilityDoctorInsurancePolicyExtendView
@end

@interface LiabilityDoctorInsurancePolicyExtendView : JSONModel

/**
* شناسه ی نرخ پوشش پزشکی
*/
@property NSString* liabilityDoctorCoverageRateId;

/**
* شناسه ی دوره های فعالیت
*/
@property NSString* activityAreaParamId;

/**
* شاسه ی تخصص
*/
@property NSString* expertiseParamId;

/**
* شناسه ی سقف تعهد
*/
@property NSString* commitmentCeilingParamId;

/**
* شناسه ی تخفیف
*/
@property NSString* insuranceRiskLevelId;

/**
* تاریخ پایان بیمه نامه
*/
@property NSString* currentInsuranceDeadline;

/**
* نرخ تخفیف پوشش
*/
@property NSString* riskLevelDiscountRate;

/**
* خسارت جانی
*/
@property NSString* physicalCommitment;

/**
* نرخ تخفیف
*/
@property NSString* discountRate;

/**
* پوشش پایه
*/
@property NSString* basePremium;

/**
* پوشش ها
*/
@property NSString* allPremium;

/**
* اطلاعات اضافه
*/
@property NSString* allExtraValues;

/**
* نرخ تخفیف شرکت بیمه
*/
@property int insuranceCompanyDiscountRate;

/**
* لیست تخفیفات
*/
@property int allDiscount;

/**
* نوع ارز حق بیمه
*/
@property int exchangePremium;

/**
* نام پزشک
*/
@property NSString* doctorName;

/**
* شماره ی نظام پزشکی
*/
@property NSString* medicalSystemNO;

/**
* آدرس
*/
@property NSString* address;

/**
* آیا رزیدنت است؟
*/
@property BOOL isResident;

/**
* آیا دانشجو است؟
*/
@property BOOL isStudent;

/**
* دارای مطب؟
*/
@property NSString* hasClinic;

/**
* شناسه ی گواهی نظام پزشکی
*/
@property NSString* metaMediaMedicalSystemLicenseId;

/**
* آدرس گواهی نظام پزشکی
*/
@property NSString* metaMediaMedicalSystemLicenseUrl;

/**
* شناسه ی کارت ملی
*/
@property NSString* metaMediaNationalCardId;

/**
* آدرس کارت ملی
*/
@property NSString* metaMediaNationalCardUrl;

/**
* شناسه ی بیمه نامه ی کنونی
*/
@property NSString* metaMediaCurrentInsurancePolicyId;

/**
* آدرس بیمه نامه ی کنونی
*/
@property NSString* metaMediaCurrentInsurancePolicyUrl;

/**
* شناسه ی دوره های بیمه نامه
*/
@property NSString* activityAreaEnumName;

/**
* نام دوره ی بیمه نامه
*/
@property NSString* activityAreaTitle;

/**
* نام تخصص
*/
@property NSString* expertiseTitle;

/**
* وضعیت پزشک
*/
@property NSString* docterStatusTitle;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif