//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_LIABILITYDOCTORINSURANCEPOLICYFILTER
#define APIMATIC_LIABILITYDOCTORINSURANCEPOLICYFILTER

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol LiabilityDoctorInsurancePolicyFilter
@end

@interface LiabilityDoctorInsurancePolicyFilter : JSONModel

/**
* TODO: Write general description for this field
*/
@property int expertiseParamId;

/**
* TODO: Write general description for this field
*/
@property BOOL isResident;

/**
* TODO: Write general description for this field
*/
@property BOOL isStudent;

/**
* TODO: Write general description for this field
*/
@property NSString* riskLevelId;

/**
* TODO: Write general description for this field
*/
@property int activityAreaParamId;

/**
* TODO: Write general description for this field
*/
@property int commitmentCeilingParamId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceExtraCoverageIds;

/**
* TODO: Write general description for this field
*/
@property NSString* policyTermId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreSubDomainName;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCompanyId;

/**
* TODO: Write general description for this field
*/
@property BOOL isSearchQuery;

/**
* TODO: Write general description for this field
*/
@property NSString* giftCode;

/**
* TODO: Write general description for this field
*/
@property NSString* customerUserId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif