//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_PORTALLANDINGCONTACTABOUT
#define APIMATIC_PORTALLANDINGCONTACTABOUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "InsuranceCentreData.h"
#import "InsuranceCentrePortal.h"


//protocol defined for deserialization of JSON
@protocol PortalLandingContactAbout
@end

@interface PortalLandingContactAbout : JSONModel

/**
* TODO: Write general description for this field
*/
@property BOOL licensed;

/**
* TODO: Write general description for this field
*/
@property NSArray* insuranceGroup;

/**
* TODO: Write general description for this field
*/
@property NSArray* insuranceType;

/**
* TODO: Write general description for this field
*/
@property NSArray* summaryCards;

/**
* TODO: Write general description for this field
*/
@property NSArray* summaryNotics;

/**
* TODO: Write general description for this field
*/
@property NSArray* imageAlbums;

/**
* TODO: Write general description for this field
*/
@property NSArray* videoGalleries;

/**
* TODO: Write general description for this field
*/
@property InsuranceCentreData* insuranceCentre;

/**
* TODO: Write general description for this field
*/
@property InsuranceCentrePortal* insuranceCentrePortal;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif