//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Status.h"

@implementation Status

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize entityId;

/**
* TODO: Write general description for this method
*/
@synthesize primaryEntityName;

/**
* TODO: Write general description for this method
*/
@synthesize statusCollectionId;

/**
* TODO: Write general description for this method
*/
@synthesize formData;

/**
* TODO: Write general description for this method
*/
@synthesize statusTitle;

/**
* TODO: Write general description for this method
*/
@synthesize editable;

/**
* TODO: Write general description for this method
*/
@synthesize statusCollectionParentId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"entityId": @"entityId",
        @"primaryEntityName": @"primaryEntityName",
        @"statusCollectionId": @"statusCollectionId",
        @"formData": @"formData",
        @"statusTitle": @"statusTitle",
        @"editable": @"editable",
        @"statusCollectionParentId": @"statusCollectionParentId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end