//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "APIError.h"
#import "HttpContext.h"
#import "Exception.h"



@interface Status400Exception : APIError
 
 /**
* TODO: Write general description for this field
*/
@property BOOL isSuccess;

/**
* TODO: Write general description for this field
*/
@property int status;

/**
* TODO: Write general description for this field
*/
@property NSString* message;

/**
* TODO: Write general description for this field
*/
@property NSString* extraData;

/**
* TODO: Write general description for this field
*/
@property Exception* exception;

- (Status400Exception*) initWithReason: (NSString*) reason
                                  andContext: (HttpContext*) context;

@end