//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATUS
#define APIMATIC_STATUS

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol Status
@end

@interface Status : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* mid;

/**
* TODO: Write general description for this field
*/
@property NSString* entityId;

/**
* TODO: Write general description for this field
*/
@property int primaryEntityName;

/**
* TODO: Write general description for this field
*/
@property NSString* statusCollectionId;

/**
* TODO: Write general description for this field
*/
@property NSString* formData;

/**
* TODO: Write general description for this field
*/
@property NSString* statusTitle;

/**
* TODO: Write general description for this field
*/
@property BOOL editable;

/**
* TODO: Write general description for this field
*/
@property NSString* statusCollectionParentId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif