//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "SummaryNotic.h"

@implementation SummaryNotic

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreId;

/**
* TODO: Write general description for this method
*/
@synthesize articleType;

/**
* TODO: Write general description for this method
*/
@synthesize title;

/**
* TODO: Write general description for this method
*/
@synthesize summary;

/**
* TODO: Write general description for this method
*/
@synthesize articleGroup;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaFileId;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaFileUrl;

/**
* TODO: Write general description for this method
*/
@synthesize publishPersianDate;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"insuranceCentreId": @"insuranceCentreId",
        @"articleType": @"articleType",
        @"title": @"title",
        @"summary": @"summary",
        @"articleGroup": @"articleGroup",
        @"metaMediaFileId": @"metaMediaFileId",
        @"metaMediaFileUrl": @"metaMediaFileUrl",
        @"publishPersianDate": @"publishPersianDate"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end