//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "TargetSite.h"

@implementation TargetSite

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize assemblyName;

/**
* TODO: Write general description for this method
*/
@synthesize className;

/**
* TODO: Write general description for this method
*/
@synthesize signature;

/**
* TODO: Write general description for this method
*/
@synthesize signature2;

/**
* TODO: Write general description for this method
*/
@synthesize memberType;

/**
* TODO: Write general description for this method
*/
@synthesize genericArguments;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"Name": @"name",
        @"AssemblyName": @"assemblyName",
        @"ClassName": @"className",
        @"Signature": @"signature",
        @"Signature2": @"signature2",
        @"MemberType": @"memberType",
        @"GenericArguments": @"genericArguments"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end