//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TARGETSITE
#define APIMATIC_TARGETSITE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol TargetSite
@end

@interface TargetSite : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* name;

/**
* TODO: Write general description for this field
*/
@property NSString* assemblyName;

/**
* TODO: Write general description for this field
*/
@property NSString* className;

/**
* TODO: Write general description for this field
*/
@property NSString* signature;

/**
* TODO: Write general description for this field
*/
@property NSString* signature2;

/**
* TODO: Write general description for this field
*/
@property int memberType;

/**
* TODO: Write general description for this field
*/
@property NSString* genericArguments;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif