//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "TrackingDamageRequest.h"

@implementation TrackingDamageRequest

/**
* TODO: Write general description for this method
*/
@synthesize personalityType;

/**
* TODO: Write general description for this method
*/
@synthesize trackingDamageStatus;

/**
* TODO: Write general description for this method
*/
@synthesize description;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceTypeId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyId;

/**
* TODO: Write general description for this method
*/
@synthesize insurancePolicyNumber;

/**
* TODO: Write general description for this method
*/
@synthesize damageType;

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize nationalCode;

/**
* TODO: Write general description for this method
*/
@synthesize mobile;

/**
* TODO: Write general description for this method
*/
@synthesize insuredProfile;

/**
* TODO: Write general description for this method
*/
@synthesize subDomain;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"personalityType": @"personalityType",
        @"trackingDamageStatus": @"trackingDamageStatus",
        @"description": @"description",
        @"insuranceTypeId": @"insuranceTypeId",
        @"insuranceCompanyId": @"insuranceCompanyId",
        @"insurancePolicyNumber": @"insurancePolicyNumber",
        @"damageType": @"damageType",
        @"name": @"name",
        @"nationalCode": @"nationalCode",
        @"mobile": @"mobile",
        @"insuredProfile": @"insuredProfile",
        @"subDomain": @"subDomain"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end