//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TRACKINGCODE
#define APIMATIC_TRACKINGCODE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "TrackingDamageStatusTrackingCode.h"


//protocol defined for deserialization of JSON
@protocol TrackingCode
@end

@interface TrackingCode : JSONModel

/**
* TODO: Write general description for this field
*/
@property int mid;

/**
* TODO: Write general description for this field
*/
@property int insuranceTypeId;

/**
* TODO: Write general description for this field
*/
@property int insuranceCentreId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreName;

/**
* TODO: Write general description for this field
*/
@property int insuranceCompanyId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCompanyTitle;

/**
* TODO: Write general description for this field
*/
@property NSString* insurancePolicyNumber;

/**
* TODO: Write general description for this field
*/
@property int personalityType;

/**
* TODO: Write general description for this field
*/
@property NSString* damageType;

/**
* TODO: Write general description for this field
*/
@property NSString* name;

/**
* TODO: Write general description for this field
*/
@property NSString* nationalCode;

/**
* TODO: Write general description for this field
*/
@property NSString* mobile;

/**
* TODO: Write general description for this field
*/
@property NSString* insuredProfile;

/**
* TODO: Write general description for this field
*/
@property NSString* refrencedUser;

/**
* TODO: Write general description for this field
*/
@property NSString* referenceCount;

/**
* TODO: Write general description for this field
*/
@property NSString* trackingCode;

/**
* TODO: Write general description for this field
*/
@property NSString* paymentType;

/**
* TODO: Write general description for this field
*/
@property NSString* paymentDate;

/**
* TODO: Write general description for this field
*/
@property NSString* paymentPersianDate;

/**
* TODO: Write general description for this field
*/
@property NSString* subDomain;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceTypeTitle;

/**
* TODO: Write general description for this field
*/
@property NSString* createOn;

/**
* TODO: Write general description for this field
*/
@property NSString* updateOn;

/**
* TODO: Write general description for this field
*/
@property NSString* createOnPersianDate;

/**
* TODO: Write general description for this field
*/
@property NSString* updateOnPersianDate;

/**
* TODO: Write general description for this field
*/
@property NSArray<TrackingDamageStatusTrackingCode> * trackingDamageStatus;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif