//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "TrackingCode.h"

@implementation TrackingCode

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceTypeId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreName;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyTitle;

/**
* TODO: Write general description for this method
*/
@synthesize insurancePolicyNumber;

/**
* TODO: Write general description for this method
*/
@synthesize personalityType;

/**
* TODO: Write general description for this method
*/
@synthesize damageType;

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize nationalCode;

/**
* TODO: Write general description for this method
*/
@synthesize mobile;

/**
* TODO: Write general description for this method
*/
@synthesize insuredProfile;

/**
* TODO: Write general description for this method
*/
@synthesize refrencedUser;

/**
* TODO: Write general description for this method
*/
@synthesize referenceCount;

/**
* TODO: Write general description for this method
*/
@synthesize trackingCode;

/**
* TODO: Write general description for this method
*/
@synthesize paymentType;

/**
* TODO: Write general description for this method
*/
@synthesize paymentDate;

/**
* TODO: Write general description for this method
*/
@synthesize paymentPersianDate;

/**
* TODO: Write general description for this method
*/
@synthesize subDomain;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceTypeTitle;

/**
* TODO: Write general description for this method
*/
@synthesize createOn;

/**
* TODO: Write general description for this method
*/
@synthesize updateOn;

/**
* TODO: Write general description for this method
*/
@synthesize createOnPersianDate;

/**
* TODO: Write general description for this method
*/
@synthesize updateOnPersianDate;

/**
* TODO: Write general description for this method
*/
@synthesize trackingDamageStatus;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"insuranceTypeId": @"insuranceTypeId",
        @"insuranceCentreId": @"insuranceCentreId",
        @"insuranceCentreName": @"insuranceCentreName",
        @"insuranceCompanyId": @"insuranceCompanyId",
        @"insuranceCompanyTitle": @"insuranceCompanyTitle",
        @"insurancePolicyNumber": @"insurancePolicyNumber",
        @"personalityType": @"personalityType",
        @"damageType": @"damageType",
        @"name": @"name",
        @"nationalCode": @"nationalCode",
        @"mobile": @"mobile",
        @"insuredProfile": @"insuredProfile",
        @"refrencedUser": @"refrencedUser",
        @"referenceCount": @"referenceCount",
        @"trackingCode": @"trackingCode",
        @"paymentType": @"paymentType",
        @"paymentDate": @"paymentDate",
        @"paymentPersianDate": @"paymentPersianDate",
        @"subDomain": @"subDomain",
        @"insuranceTypeTitle": @"insuranceTypeTitle",
        @"createOn": @"createOn",
        @"updateOn": @"updateOn",
        @"createOnPersianDate": @"createOnPersianDate",
        @"updateOnPersianDate": @"updateOnPersianDate",
        @"trackingDamageStatus": @"trackingDamageStatus"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end