//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "TravelInsurance.h"

@implementation TravelInsurance

/**
* TODO: Write general description for this method
*/
@synthesize hasPlan;

/**
* TODO: Write general description for this method
*/
@synthesize isSamanInsurance;

/**
* TODO: Write general description for this method
*/
@synthesize zones;

/**
* TODO: Write general description for this method
*/
@synthesize travelDurations;

/**
* TODO: Write general description for this method
*/
@synthesize travelAges;

/**
* TODO: Write general description for this method
*/
@synthesize provinces;

/**
* TODO: Write general description for this method
*/
@synthesize cities;

/**
* TODO: Write general description for this method
*/
@synthesize cityRegions;

/**
* TODO: Write general description for this method
*/
@synthesize shippingTypes;

/**
* TODO: Write general description for this method
*/
@synthesize postTypes;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceData;

/**
* TODO: Write general description for this method
*/
@synthesize insurancePolicyCondition;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"hasPlan": @"hasPlan",
        @"isSamanInsurance": @"isSamanInsurance",
        @"zones": @"zones",
        @"travelDurations": @"travelDurations",
        @"travelAges": @"travelAges",
        @"provinces": @"provinces",
        @"cities": @"cities",
        @"cityRegions": @"cityRegions",
        @"shippingTypes": @"shippingTypes",
        @"postTypes": @"postTypes",
        @"insuranceData": @"insuranceData",
        @"insurancePolicyCondition": @"insurancePolicyCondition"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end