//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TRAVELINSURANCEPOLICYEXTEND
#define APIMATIC_TRAVELINSURANCEPOLICYEXTEND

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol TravelInsurancePolicyExtend
@end

@interface TravelInsurancePolicyExtend : JSONModel

/**
* TODO: Write general description for this field
*/
@property int insurancePolicyId;

/**
* TODO: Write general description for this field
*/
@property NSString* travelDurationParam;

/**
* TODO: Write general description for this field
*/
@property int passengersCount;

/**
* TODO: Write general description for this field
*/
@property NSString* birthDate;

/**
* TODO: Write general description for this field
*/
@property NSString* birthDatePersian;

/**
* TODO: Write general description for this field
*/
@property int riskLevelDiscount;

/**
* TODO: Write general description for this field
*/
@property NSString* basePremium;

/**
* TODO: Write general description for this field
*/
@property NSString* allPremium;

/**
* TODO: Write general description for this field
*/
@property int insuranceCompanyDiscountRate;

/**
* TODO: Write general description for this field
*/
@property int insuranceCompanyDiscount;

/**
* TODO: Write general description for this field
*/
@property int insuranceCentreDiscount;

/**
* TODO: Write general description for this field
*/
@property int coupenDiscount;

/**
* TODO: Write general description for this field
*/
@property int allDiscount;

/**
* TODO: Write general description for this field
*/
@property int exchangePremium;

/**
* TODO: Write general description for this field
*/
@property NSString* travelRatePlanId;

/**
* TODO: Write general description for this field
*/
@property NSString* planTitle;

/**
* TODO: Write general description for this field
*/
@property NSString* travelInsurancePolicyExtendAges;

/**
* TODO: Write general description for this field
*/
@property NSString* travelInsurancePolicyExtendPassengers;

/**
* TODO: Write general description for this field
*/
@property NSString* zoneIds;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif