//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "TravelInsurancePolicyExtend.h"

@implementation TravelInsurancePolicyExtend

/**
* TODO: Write general description for this method
*/
@synthesize insurancePolicyId;

/**
* TODO: Write general description for this method
*/
@synthesize travelDurationParam;

/**
* TODO: Write general description for this method
*/
@synthesize passengersCount;

/**
* TODO: Write general description for this method
*/
@synthesize birthDate;

/**
* TODO: Write general description for this method
*/
@synthesize birthDatePersian;

/**
* TODO: Write general description for this method
*/
@synthesize riskLevelDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize basePremium;

/**
* TODO: Write general description for this method
*/
@synthesize allPremium;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyDiscountRate;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize coupenDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize allDiscount;

/**
* TODO: Write general description for this method
*/
@synthesize exchangePremium;

/**
* TODO: Write general description for this method
*/
@synthesize travelRatePlanId;

/**
* TODO: Write general description for this method
*/
@synthesize planTitle;

/**
* TODO: Write general description for this method
*/
@synthesize travelInsurancePolicyExtendAges;

/**
* TODO: Write general description for this method
*/
@synthesize travelInsurancePolicyExtendPassengers;

/**
* TODO: Write general description for this method
*/
@synthesize zoneIds;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"insurancePolicyId": @"insurancePolicyId",
        @"travelDurationParam": @"travelDurationParam",
        @"passengersCount": @"passengersCount",
        @"birthDate": @"birthDate",
        @"birthDatePersian": @"birthDatePersian",
        @"riskLevelDiscount": @"riskLevelDiscount",
        @"basePremium": @"basePremium",
        @"allPremium": @"allPremium",
        @"insuranceCompanyDiscountRate": @"insuranceCompanyDiscountRate",
        @"insuranceCompanyDiscount": @"insuranceCompanyDiscount",
        @"insuranceCentreDiscount": @"insuranceCentreDiscount",
        @"coupenDiscount": @"coupenDiscount",
        @"allDiscount": @"allDiscount",
        @"exchangePremium": @"exchangePremium",
        @"travelRatePlanId": @"travelRatePlanId",
        @"planTitle": @"planTitle",
        @"travelInsurancePolicyExtendAges": @"travelInsurancePolicyExtendAges",
        @"travelInsurancePolicyExtendPassengers": @"travelInsurancePolicyExtendPassengers",
        @"zoneIds": @"zoneIds"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end