//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "TravelInsurancePolicyFilter.h"

@implementation TravelInsurancePolicyFilter

/**
* TODO: Write general description for this method
*/
@synthesize zoneIds;

/**
* TODO: Write general description for this method
*/
@synthesize travelRatePlanId;

/**
* TODO: Write general description for this method
*/
@synthesize travelInsurancePolicyExtendAges;

/**
* TODO: Write general description for this method
*/
@synthesize travelDurationParam;

/**
* TODO: Write general description for this method
*/
@synthesize birthDatePersian;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceExtraCoverageIds;

/**
* TODO: Write general description for this method
*/
@synthesize policyTermId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreSubDomainName;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCentreId;

/**
* TODO: Write general description for this method
*/
@synthesize insuranceCompanyId;

/**
* TODO: Write general description for this method
*/
@synthesize isSearchQuery;

/**
* TODO: Write general description for this method
*/
@synthesize giftCode;

/**
* TODO: Write general description for this method
*/
@synthesize customerUserId;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"zoneIds": @"zoneIds",
        @"travelRatePlanId": @"travelRatePlanId",
        @"travelInsurancePolicyExtendAges": @"travelInsurancePolicyExtendAges",
        @"travelDurationParam": @"travelDurationParam",
        @"birthDatePersian": @"birthDatePersian",
        @"insuranceExtraCoverageIds": @"insuranceExtraCoverageIds",
        @"policyTermId": @"policyTermId",
        @"insuranceCentreSubDomainName": @"insuranceCentreSubDomainName",
        @"insuranceCentreId": @"insuranceCentreId",
        @"insuranceCompanyId": @"insuranceCompanyId",
        @"isSearchQuery": @"isSearchQuery",
        @"giftCode": @"giftCode",
        @"customerUserId": @"customerUserId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end