//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TRAVELINSURANCE
#define APIMATIC_TRAVELINSURANCE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Zone.h"
#import "TravelDuration.h"
#import "TravelAge.h"
#import "Province.h"
#import "ShippingType.h"
#import "PostType.h"
#import "InsuranceDataTravelInsurance.h"
#import "InsurancePolicyCondition.h"


//protocol defined for deserialization of JSON
@protocol TravelInsurance
@end

@interface TravelInsurance : JSONModel

/**
* TODO: Write general description for this field
*/
@property BOOL hasPlan;

/**
* TODO: Write general description for this field
*/
@property BOOL isSamanInsurance;

/**
* TODO: Write general description for this field
*/
@property NSArray<Zone> * zones;

/**
* TODO: Write general description for this field
*/
@property NSArray<TravelDuration> * travelDurations;

/**
* TODO: Write general description for this field
*/
@property NSArray<TravelAge> * travelAges;

/**
* TODO: Write general description for this field
*/
@property NSArray<Province> * provinces;

/**
* TODO: Write general description for this field
*/
@property NSArray* cities;

/**
* TODO: Write general description for this field
*/
@property NSArray* cityRegions;

/**
* TODO: Write general description for this field
*/
@property NSArray<ShippingType> * shippingTypes;

/**
* TODO: Write general description for this field
*/
@property NSArray<PostType> * postTypes;

/**
* TODO: Write general description for this field
*/
@property InsuranceDataTravelInsurance* insuranceData;

/**
* TODO: Write general description for this field
*/
@property InsurancePolicyCondition* insurancePolicyCondition;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif