//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TRAVELINSURANCEPOLICYFILTER
#define APIMATIC_TRAVELINSURANCEPOLICYFILTER

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol TravelInsurancePolicyFilter
@end

@interface TravelInsurancePolicyFilter : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* zoneIds;

/**
* TODO: Write general description for this field
*/
@property NSString* travelRatePlanId;

/**
* TODO: Write general description for this field
*/
@property NSString* travelInsurancePolicyExtendAges;

/**
* TODO: Write general description for this field
*/
@property NSString* travelDurationParam;

/**
* TODO: Write general description for this field
*/
@property NSString* birthDatePersian;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceExtraCoverageIds;

/**
* TODO: Write general description for this field
*/
@property NSString* policyTermId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreSubDomainName;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCentreId;

/**
* TODO: Write general description for this field
*/
@property NSString* insuranceCompanyId;

/**
* TODO: Write general description for this field
*/
@property BOOL isSearchQuery;

/**
* TODO: Write general description for this field
*/
@property NSString* giftCode;

/**
* TODO: Write general description for this field
*/
@property NSString* customerUserId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif