//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Upload.h"

@implementation Upload

/**
* شناسه ی فایل
*/
@synthesize mid;

/**
* شناسه ی دایرکتوری فایل
*/
@synthesize metaMediaDirectoryId;

/**
* عنوان
*/
@synthesize title;

/**
* توضیح فایل
*/
@synthesize alt;

/**
* نام فایل
*/
@synthesize fileName;

/**
* پسورد فایل
*/
@synthesize passwordHash;

/**
* وضعیت اکتیو بودن فایل
*/
@synthesize isActive;

/**
* زمان انقضای فایل
*/
@synthesize expireOn;

/**
* لیبل دسته بندی فایل
*/
@synthesize fileLibraryLabelParam;

/**
* اندازه ی فایل
*/
@synthesize fileSize;

/**
* اندازه ی فایل
*/
@synthesize fileSizeValue;

/**
* آدرس فایل
*/
@synthesize fileUrl;

/**
* آدرس پیش نمایش فایل
*/
@synthesize fileThumbnailUrl;

/**
* تاریخ انقضای شمسی
*/
@synthesize expireOnPersianDate;

/**
* تاریخ بروز رسانی فایل
*/
@synthesize updateOn;

/**
* تاریخ ثبت فایل
*/
@synthesize createOn;

/**
* تاریخ ثبت فایل شمسی
*/
@synthesize createOnPersianDate;

/**
* تاریخ بروز رسانی فایل شمسی
*/
@synthesize updateOnPersianDate;

/**
* آدرس دایرکتوری فایل
*/
@synthesize filePath;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"metaMediaDirectoryId": @"metaMediaDirectoryId",
        @"title": @"title",
        @"alt": @"alt",
        @"fileName": @"fileName",
        @"passwordHash": @"passwordHash",
        @"isActive": @"isActive",
        @"expireOn": @"expireOn",
        @"fileLibraryLabelParam": @"fileLibraryLabelParam",
        @"fileSize": @"fileSize",
        @"fileSizeValue": @"fileSizeValue",
        @"fileUrl": @"fileUrl",
        @"fileThumbnailUrl": @"fileThumbnailUrl",
        @"expireOnPersianDate": @"expireOnPersianDate",
        @"updateOn": @"updateOn",
        @"createOn": @"createOn",
        @"createOnPersianDate": @"createOnPersianDate",
        @"updateOnPersianDate": @"updateOnPersianDate",
        @"filePath": @"filePath"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end