//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "VideoGallery.h"

@implementation VideoGallery

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize galleryType;

/**
* TODO: Write general description for this method
*/
@synthesize title;

/**
* TODO: Write general description for this method
*/
@synthesize alt;

/**
* TODO: Write general description for this method
*/
@synthesize description;

/**
* TODO: Write general description for this method
*/
@synthesize isActive;

/**
* TODO: Write general description for this method
*/
@synthesize isMain;

/**
* TODO: Write general description for this method
*/
@synthesize isAttachFile;

/**
* TODO: Write general description for this method
*/
@synthesize sortPriority;

/**
* TODO: Write general description for this method
*/
@synthesize createOnPersianDate;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaFileId;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaFileUrl;

/**
* TODO: Write general description for this method
*/
@synthesize metaMediaFileThumbnailUrl;

/**
* TODO: Write general description for this method
*/
@synthesize popupImageGalleryies;

/**
* TODO: Write general description for this method
*/
@synthesize galleryDetails;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"galleryType": @"galleryType",
        @"title": @"title",
        @"alt": @"alt",
        @"description": @"description",
        @"isActive": @"isActive",
        @"isMain": @"isMain",
        @"isAttachFile": @"isAttachFile",
        @"sortPriority": @"sortPriority",
        @"createOnPersianDate": @"createOnPersianDate",
        @"metaMediaFileId": @"metaMediaFileId",
        @"metaMediaFileUrl": @"metaMediaFileUrl",
        @"metaMediaFileThumbnailUrl": @"metaMediaFileThumbnailUrl",
        @"popupImageGalleryies": @"popupImageGalleryies",
        @"galleryDetails": @"galleryDetails"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end