//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef EasyBimehLanding_Configuration_h
#define EasyBimehLanding_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

#endif
