//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "BaseModelDamageType.h"
#import "InsuranceTypes.h"
#import "InsuranceCompanies.h"

@interface ComboDataController : BaseController

/**
* Completion block definition for asynchronous call to DamageType */
typedef void (^CompletedGetDamageType)(BOOL success, HttpContext* context, BaseModelDamageType* response, NSError* error);

/**
* دریافت لیست نوع خسارت
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getDamageTypeAsyncWithXApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetDamageType) onCompleted;

/**
* Completion block definition for asynchronous call to InsuranceTypes */
typedef void (^CompletedGetInsuranceTypes)(BOOL success, HttpContext* context, InsuranceTypes* response, NSError* error);

/**
* دریافت لیست نوع بیمه نامه
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    issueInsurance    Required parameter: دریافت بیمه نامه های قابل صدور
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getInsuranceTypesAsyncWithSubDomain:(NSString*) subDomain
                issueInsurance:(BOOL) issueInsurance
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetInsuranceTypes) onCompleted;

/**
* Completion block definition for asynchronous call to InsuranceCompanies */
typedef void (^CompletedGetInsuranceCompanies)(BOOL success, HttpContext* context, InsuranceCompanies* response, NSError* error);

/**
* دریافت لیست شرکت های بیمه
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    insuranceTypeId    Required parameter: شناسه ی نوع بیمه نامه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getInsuranceCompaniesAsyncWithSubDomain:(NSString*) subDomain
                insuranceTypeId:(int) insuranceTypeId
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetInsuranceCompanies) onCompleted;

@end