//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "BaseModelEarthquake.h"

@interface EarthquakeInsuranceController : BaseController

/**
* Completion block definition for asynchronous call to Earthquake */
typedef void (^CompletedGetEarthquake)(BOOL success, HttpContext* context, BaseModelEarthquake* response, NSError* error);

/**
* دریافت اطلاعات پایه ی بیمه ی زلزله
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    insurancePolicyId    Required parameter: شناسه ی بیمه نامه
* @param    insurancePolicyType    Required parameter: شناسه ی نوع بیمه نامه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getEarthquakeAsyncWithSubDomain:(NSString*) subDomain
                insurancePolicyId:(int) insurancePolicyId
                insurancePolicyType:(int) insurancePolicyType
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetEarthquake) onCompleted;

@end