//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "BaseModelElectronicEquipmentInsurance.h"
#import "BaseModelDeviceBrandTypes.h"
#import "BaseModelDiviceFranchisee.h"

@interface ElectronicEquipmentInsuranceController : BaseController

/**
* Completion block definition for asynchronous call to ElectronicEquipmentInsurance */
typedef void (^CompletedGetElectronicEquipmentInsurance)(BOOL success, HttpContext* context, BaseModelElectronicEquipmentInsurance* response, NSError* error);

/**
* دریافت اطلاعات اولیه استعلام بیمه نامه ی تجهیزات الکترونیک
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getElectronicEquipmentInsuranceAsyncWithSubDomain:(NSString*) subDomain
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetElectronicEquipmentInsurance) onCompleted;

/**
* Completion block definition for asynchronous call to DeviceBrandTypes */
typedef void (^CompletedGetDeviceBrandTypes)(BOOL success, HttpContext* context, BaseModelDeviceBrandTypes* response, NSError* error);

/**
* دریافت لیست نوع برند دستگاه
* @param    deviceGroup    Required parameter: شناسه ی گروه دستگاه
* @param    deviceTypeId    Required parameter: شناسه ی نوع دستگاه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getDeviceBrandTypesAsyncWithDeviceGroup:(int) deviceGroup
                deviceTypeId:(int) deviceTypeId
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetDeviceBrandTypes) onCompleted;

/**
* Completion block definition for asynchronous call to DiviceFranchisee */
typedef void (^CompletedGetDiviceFranchisee)(BOOL success, HttpContext* context, BaseModelDiviceFranchisee* response, NSError* error);

/**
* دریافت لیست فرانشیر استعلام بیمه نامه ی تجهیزات الکترونیک
* @param    deviceModelId    Required parameter: شناسه ی مدل دستگاه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getDiviceFranchiseeAsyncWithDeviceModelId:(int) deviceModelId
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetDiviceFranchisee) onCompleted;

@end