//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "BaseModelElevatorInsurance.h"

@interface ElevatorInsuranceController : BaseController

/**
* Completion block definition for asynchronous call to ElevatorInsurance */
typedef void (^CompletedGetElevatorInsurance)(BOOL success, HttpContext* context, BaseModelElevatorInsurance* response, NSError* error);

/**
* دریافت اطلاعات پایه ی بیمه نامه ی آسانسور
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    insurancePolicyId    Required parameter: شناسه ی بیمه نامه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getElevatorInsuranceAsyncWithSubDomain:(NSString*) subDomain
                insurancePolicyId:(int) insurancePolicyId
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetElevatorInsurance) onCompleted;

@end