//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "BaseModelUpload.h"

@interface FileManagerController : BaseController

/**
* Completion block definition for asynchronous call to Upload */
typedef void (^CompletedPostUpload)(BOOL success, HttpContext* context, BaseModelUpload* response, NSError* error);

/**
* آپلود فایل در ایزی بیمه
* بعد از آپلود، ادرس فایل باید در api های بعدی ارسال شود.
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
* @param    file    Required parameter: فایل ارسالی
*/
- (void) uploadAsyncWithSubDomain:(NSString*) subDomain
                xApiKey:(NSString*) xApiKey
                file:(NSString*) file
                completionBlock:(CompletedPostUpload) onCompleted;

@end