//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "BaseModelFireInsurance.h"

@interface FireInsuranceController : BaseController

/**
* Completion block definition for asynchronous call to FireInsurance */
typedef void (^CompletedGetFireInsurance)(BOOL success, HttpContext* context, BaseModelFireInsurance* response, NSError* error);

/**
* دریافت اطلاعات پایه بیمه ی آتش سوزی
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    insurancePolicyId    Required parameter: شناسه ی بیمه نامه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getFireInsuranceAsyncWithSubDomain:(NSString*) subDomain
                insurancePolicyId:(int) insurancePolicyId
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetFireInsurance) onCompleted;

@end