//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "BaseModelPortalLandingContactAbout.h"
#import "BaseModelFaqInsuranceCentre.h"
#import "BaseModelInsurancePolicyTracking.h"
#import "InternalServerErrorException.h"

@interface FooterController : BaseController

/**
* Completion block definition for asynchronous call to PortalLandingContactAbout */
typedef void (^CompletedGetPortalLandingContactAbout)(BOOL success, HttpContext* context, BaseModelPortalLandingContactAbout* response, NSError* error);

/**
* دریافت اطلاعات درباره ی ما
* @param    xApiKey    Required parameter: Example: 
*/
- (void) getPortalLandingContactAboutAsyncWithXApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetPortalLandingContactAbout) onCompleted;

/**
* Completion block definition for asynchronous call to Faq/InsuranceCentre */
typedef void (^CompletedGetFaqInsuranceCentre)(BOOL success, HttpContext* context, BaseModelFaqInsuranceCentre* response, NSError* error);

/**
* دریافت لیست سوالات متداول
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getFaqInsuranceCentreAsyncWithXApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetFaqInsuranceCentre) onCompleted;

/**
* Completion block definition for asynchronous call to InsurancePolicy/Tracking */
typedef void (^CompletedGetInsurancePolicyTracking)(BOOL success, HttpContext* context, BaseModelInsurancePolicyTracking* response, NSError* error);

/**
* پیگیری وضعیت بیمه نامه
* @param    trackingCode    Required parameter: شماره ی پیگیری بیمه نامه
* @param    nationalCode    Required parameter: کد ملی کاربر
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getInsurancePolicyTrackingAsyncWithTrackingCode:(int) trackingCode
                nationalCode:(long) nationalCode
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetInsurancePolicyTracking) onCompleted;

@end