//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "BaseModelLiabilityDoctorInsurance.h"
#import "BaseModelMedicalSpecialties.h"

@interface LiabilityDoctorInsuranceController : BaseController

/**
* Completion block definition for asynchronous call to LiabilityDoctorInsurance */
typedef void (^CompletedGetLiabilityDoctorInsurance)(BOOL success, HttpContext* context, BaseModelLiabilityDoctorInsurance* response, NSError* error);

/**
* در یافت اطلاعات اولیه برای استعلام بیمه مسئولیت پزشکان
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getLiabilityDoctorInsuranceAsyncWithSubDomain:(NSString*) subDomain
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetLiabilityDoctorInsurance) onCompleted;

/**
* Completion block definition for asynchronous call to MedicalSpecialties */
typedef void (^CompletedGetMedicalSpecialties)(BOOL success, HttpContext* context, BaseModelMedicalSpecialties* response, NSError* error);

/**
* دریافت لیست تخصص های پزشکی
* @param    mid    Required parameter: نوع تخصص => ParamedicalExpertise => پیراپزشکی MedicalExpertise => پزشکی
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getMedicalSpecialtiesAsyncWithId:(NSString*) mid
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetMedicalSpecialties) onCompleted;

@end