//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CarBrands.h"
#import "CarBrandTips.h"
#import "HasPlan.h"

@interface MotorcycleInsuranceController : BaseController

/**
* Completion block definition for asynchronous call to CarBrands */
typedef void (^CompletedGetCarBrands)(BOOL success, HttpContext* context, CarBrands* response, NSError* error);

/**
* دریافت لیست برند موتور سیکلت
* @param    carTypeGroup    Required parameter: شناسه ی گروه خودرویی، موتور سیکلت =>0
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getCarBrandsAsyncWithCarTypeGroup:(int) carTypeGroup
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetCarBrands) onCompleted;

/**
* Completion block definition for asynchronous call to CarBrandTips */
typedef void (^CompletedGetCarBrandTips)(BOOL success, HttpContext* context, CarBrandTips* response, NSError* error);

/**
* دریافت لیست تیپ موتور سیکلت
* @param    carBrandId    Required parameter: شناسه ی برند موتور سیکلت
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getCarBrandTipsAsyncWithCarBrandId:(int) carBrandId
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetCarBrandTips) onCompleted;

/**
* Completion block definition for asynchronous call to HasPlan */
typedef void (^CompletedGetHasPlan)(BOOL success, HttpContext* context, HasPlan* response, NSError* error);

/**
* آیا این نوع بیمه نامه، طرح بیمه ای دارد؟
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    insurancePolicyType    Required parameter: شناسه ی نوع بیمه نامه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getHasPlanAsyncWithSubDomain:(NSString*) subDomain
                insurancePolicyType:(int) insurancePolicyType
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetHasPlan) onCompleted;

@end