//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "OtherInsuranceTypes.h"
#import "SendSmsToken.h"
#import "Status200.h"
#import "Status400Exception.h"

@interface OtherInsuranceTypesController : BaseController

/**
* Completion block definition for asynchronous call to OtherInsuranceTypes */
typedef void (^CompletedGetOtherInsuranceTypes)(BOOL success, HttpContext* context, OtherInsuranceTypes* response, NSError* error);

/**
* دریافت لیست سایر بیمه نامه ها
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getOtherInsuranceTypesAsyncWithSubDomain:(NSString*) subDomain
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetOtherInsuranceTypes) onCompleted;

/**
* Completion block definition for asynchronous call to SendSmsToken */
typedef void (^CompletedGetSendSmsToken)(BOOL success, HttpContext* context, SendSmsToken* response, NSError* error);

/**
* ارسال توکن تایید شماره تماس، برای احراز هویت کاربر
* @param    mobile    Required parameter: شماره موبایل
* @param    insuranceCentreSubDomain    Required parameter: دامنه یا زیردامنه ی مرکز بیمه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getSendSmsTokenAsyncWithMobile:(NSString*) mobile
                insuranceCentreSubDomain:(NSString*) insuranceCentreSubDomain
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetSendSmsToken) onCompleted;

/**
* Completion block definition for asynchronous call to verifySmsToken */
typedef void (^CompletedGetVerifySmsToken)(BOOL success, HttpContext* context, Status200* response, NSError* error);

/**
* تایید توکن پیامک شده به کاربر، برای احراز هویت
* @param    mobile    Required parameter: شماره موبایل
* @param    token    Required parameter: توکن دریافتی کاربر از پیامک
* @param    insuranceCentreSubDomain    Required parameter: دامنه یا زیر دامنه ی اختصاصی مرکز بیمه
* @param    aliasName    Required parameter: نام و نام خانوادگی کاربر
* @param    resource    Required parameter: دامنه ی درخواست دهنده
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getVerifySmsTokenAsyncWithMobile:(NSString*) mobile
                token:(int) token
                insuranceCentreSubDomain:(NSString*) insuranceCentreSubDomain
                aliasName:(NSString*) aliasName
                resource:(NSString*) resource
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetVerifySmsToken) onCompleted;

@end