//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CarBrands.h"
#import "RiskLevel.h"
#import "CarBrandTips.h"
#import "CarUses.h"
#import "HasPlan.h"

@interface ThirdPartyInsuranceController : BaseController

/**
* Completion block definition for asynchronous call to CarBrands */
typedef void (^CompletedGetCarBrands)(BOOL success, HttpContext* context, CarBrands* response, NSError* error);

/**
* دریافت لیست برند خودرو ها
* @param    carTypeGroup    Required parameter: شناسه ی گروه خودرو
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getCarBrandsAsyncWithCarTypeGroup:(int) carTypeGroup
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetCarBrands) onCompleted;

/**
* Completion block definition for asynchronous call to RiskLevel */
typedef void (^CompletedGetRiskLevel)(BOOL success, HttpContext* context, RiskLevel* response, NSError* error);

/**
* دریافت لیست تخفیف های بیمه
* @param    insurancePolicyType    Required parameter: شناسه ی نوع بیمه نامه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getRiskLevelAsyncWithInsurancePolicyType:(int) insurancePolicyType
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetRiskLevel) onCompleted;

/**
* Completion block definition for asynchronous call to CarBrandTips */
typedef void (^CompletedGetCarBrandTips)(BOOL success, HttpContext* context, CarBrandTips* response, NSError* error);

/**
* دریافت لیست تیپ خودرو
* @param    carBrandId    Required parameter: شناسه ی برند خودرو
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getCarBrandTipsAsyncWithCarBrandId:(int) carBrandId
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetCarBrandTips) onCompleted;

/**
* Completion block definition for asynchronous call to CarUses */
typedef void (^CompletedGetCarUses)(BOOL success, HttpContext* context, CarUses* response, NSError* error);

/**
* دریافت لیست نوع کاربری خودرو
* @param    carTypeId    Required parameter: شناسه ی نوع خودرو
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getCarUsesAsyncWithCarTypeId:(int) carTypeId
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetCarUses) onCompleted;

/**
* Completion block definition for asynchronous call to HasPlan */
typedef void (^CompletedGetHasPlan)(BOOL success, HttpContext* context, HasPlan* response, NSError* error);

/**
* آیا این نوع بیمه نامه، طرح بیمه ای دارد؟
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    insurancePolicyType    Required parameter: شناسه ی نوع بیمه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getHasPlanAsyncWithSubDomain:(NSString*) subDomain
                insurancePolicyType:(int) insurancePolicyType
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetHasPlan) onCompleted;

@end