//
//  EasyBimehLanding
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "BaseModelTravelInsurance.h"

@interface TravelInsuranceController : BaseController

/**
* Completion block definition for asynchronous call to TravelInsurance */
typedef void (^CompletedGetTravelInsurance)(BOOL success, HttpContext* context, BaseModelTravelInsurance* response, NSError* error);

/**
* TODO: Add Description
* @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
* @param    insurancePolicyId    Required parameter: شناسه ی بیمه نامه
* @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
*/
- (void) getTravelInsuranceAsyncWithSubDomain:(NSString*) subDomain
                insurancePolicyId:(int) insurancePolicyId
                xApiKey:(NSString*) xApiKey
                completionBlock:(CompletedGetTravelInsurance) onCompleted;

@end